<?php
use Drupal\node\NodeInterface;
/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_translation_preprocess_node(&$variables) {

  // Make sure we have a node object that works on revisions, diffs, etc.
  _sfgovpl_node_object($variables);

  if (!empty($variables['node']) && $variables['node'] instanceof NodeInterface) {
    $node = $variables['node'];
    $content_type = $node->bundle();
    $view_mode = $variables['view_mode'];

    // If the current language matches an existing Drupal translation,
    // show the Drupal-translated node and do not let Google translate it.
    $node_languages = $node->getTranslationLanguages();
    $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();;
    foreach ($node_languages as $language => $value) {
      if ($current_language == $language && $language != 'en') {

        // Do not let Google translate full pages that are not in English.
        if ($view_mode == 'full') {
          $variables['attributes']['class'][] = 'notranslate';
        }

        // If they exist, use Drupal-translated cards for transactions.
        elseif ($view_mode == 'card' && $content_type == 'transaction') {
          $variables['attributes']['class'][] = 'notranslate';
          $translated = $node->getTranslation($language);
          $variables['node'] = $translated;
          $variables['url'] = $translated->toUrl();
        }
      }
    }
  }
}
