tmgmt.translator.settings.test_translator:
  type: tmgmt.translator_base
  mapping:
    expose_settings:
      type: boolean
      label: Expose settings
    action:
      type: string
      label: Action
    key:
      type: string
      label: Key
    new_key:
      type: string
      label: New key
    another_key:
      type: string
      label: Another key
