context:
  items:
    - title: "Service card 1"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac. Quisque vitae nisl lectus. Morbi semper ante purus, eget porta magna eleifend at."
    - title: "Service card 2"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum purus odio, ut dictum justo scelerisque ac."
    - title: "Service card 3"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    - title: "Service card 4"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."