tips:
  views-ui-format:
    label: 輸出格式
  views-ui-fields:
    label: 欄位
  views-ui-filter-operations:
    body: 新增、重排或移除過濾條件。
  views-ui-sorts:
    label: 排序的標準
  views-ui-sorts-operations:
    body: 新增、重排或移除規則。
  views-ui-preview:
    label: 預覽
