label: 翻譯
tips:
  locale-overview:
    label: 使用者介面翻譯
  locale-language:
    label: 翻譯語言
    body: 選擇您要翻譯的語言。
  locale-search:
    label: 搜尋
  locale-filter:
    label: 篩選搜尋
  locale-submit:
    label: 套用您的搜尋條件
  locale-translate:
    label: 翻譯
  locale-validate:
    label: 驗證此翻譯
