cancel_confirm:
  subject: '使用者 [user:display-name] 在 [site:name] 網站上的取消帳號請求'
register_admin_created:
  subject: '[site:name] 的站台管理者已經為您建立一組帳號'
register_no_approval_required:
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情'
register_pending_approval:
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情 (等待管理者審核中)'
register_pending_approval_admin:
  body: "[使用者:display-name] 申請了帳號。\r\n\r\n[使用者:edit-url]"
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情 (等待管理者審核中)'
status_activated:
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情 (審核通過)'
status_blocked:
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情 (已封鎖)'
status_canceled:
  body: "[user:display-name]：\r\n\r\n您在 [site:name] 的帳號已經被取消\r\n\r\n--  [site:name] 團隊"
  subject: '[user:display-name] 在 [site:name] 上的帳號詳情 (已撤消)'
