label: 媒體
display:
  default:
    display_title: Default
    display_options:
      title: 媒體
      fields:
        media_bulk_form:
          action_title: 動作
        thumbnail__target_id:
          label: 縮圖
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
            format_custom_true: Published
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      empty:
        area_text_custom:
          content: 'No content available.'
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
  media_page_list:
    display_title: 媒體
    display_options:
      menu:
        title: 媒體
