display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      fields:
        node_bulk_form:
          action_title: 動作
        title:
          label: 標題
        name:
          label: 作者
        status:
          label: 狀態
          settings:
            format_custom_true: 已發表
            format_custom_false: 尚未發佈
        operations:
          label: 操作
      filters:
        title:
          expose:
            label: 標題
        type:
          expose:
            label: 內容類型
        status:
          expose:
            label: 狀態
          group_info:
            label: 發佈狀態
            group_items:
              1:
                title: 已發表
              2:
                title: 尚未發佈
        langcode:
          expose:
            label: 語言
  overview:
    display_options:
      tab_options:
        title: 內容
  user_page:
    display_options:
      tab_options:
        title: 內容
      arguments:
        uid:
          exception:
            title: 所有
