display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            first: '« 最前'
            last: '最後 »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      fields:
        title:
          label: 標題
        type:
          label: 內容類型
        status:
          label: 狀態
          settings:
            format_custom_true: 已發表
            format_custom_false: 尚未發佈
        changed:
          label: 已更新
        dropbutton:
          label: 操作
      filters:
        status:
          expose:
            label: 發佈狀態
          group_info:
            label: 發佈狀態
            group_items:
              1:
                title: 已發表
              2:
                title: 尚未發佈
        type:
          expose:
            label: 類型
      empty:
        area_text_custom:
          content: 沒有可用的內容。
      arguments:
        gid:
          exception:
            title: 所有
  page_1:
    display_title: 頁面
