display:
  default:
    display_title: Default
    display_options:
      fields:
        info:
          separator: ', '
        type:
          separator: ', '
        changed:
          label: Updated
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
  page_1:
    display_title: 頁面
