label: 最新回應
description: 最近的回應
display:
  default:
    display_options:
      title: 最新回應
      empty:
        area_text_custom:
          content: 沒有回應。
  block_1:
    display_title: 區塊
    display_options:
      block_description: 最新回應
      block_category: '列表 (Views)'
