label: 新進成員
description: 顯示網站上最新的使用者列表。
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      title: 新進成員
  block_1:
    display_title: 新進成員
    display_options:
      display_description: 新使用者列表
      block_description: 新進成員
      block_category: 使用者
