display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
        name:
          label: Author
        changed:
          label: Updated
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        langcode:
          expose:
            label: Language
