label: 首頁
description: 所有推薦到首頁的內容。
display:
  default:
    display_options:
      empty:
        title:
          title: '歡迎來到 [site:name]'
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 最前'
            last: '最後 »'
  feed_1:
    display_title: 摘要
  page_1:
    display_title: 頁面
