label: Scheduled
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 第一頁'
            last: '最後一頁 »'
      fields:
        node_bulk_form:
          action_title: 動作
        title:
          label: Title
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Scheduled
  overview:
    display_options:
      menu:
        title: Scheduled
      tab_options:
        title: 內容
  user_page:
    display_options:
      tab_options:
        title: 內容
      arguments:
        uid:
          exception:
            title: All
    display_title: 'User profile tab'
