display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        state:
          label: State
        label:
          label: Label
        type:
          label: Type
        source_language:
          label: 寄件人
          separator: ', '
        target_language:
          label: 收件人
          separator: ', '
        word_count:
          separator: ', '
        tags_count:
          label: '標籤 (Tags)'
          separator: ', '
        changed:
          label: 已變更
          separator: ', '
        operations:
          label: Operations
      filters:
        state:
          expose:
            label: 狀態
          group_info:
            label: State
        source_language:
          expose:
            label: 源語言
        job_type:
          group_info:
            group_items:
              1:
                title: 標準的
  page_1:
    display_title: 頁面
