label: 使用者
description: 尋找及管理網站使用者。
display:
  default:
    display_title: Default
    display_options:
      title: 使用者
      fields:
        user_bulk_form:
          label: 批量更新
        name:
          label: 使用者名稱
        status:
          label: Status
          settings:
            format_custom_false: 封鎖
            format_custom_true: 啟用
        roles_target_id:
          label: 角色
        created:
          label: 註冊了
        access:
          label: 最近存取時間
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      empty:
        area_text_custom:
          content: 沒有使用者
      filters:
        combine:
          expose:
            label: 包含使用者名稱或電子郵件
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: 啟用
              2:
                title: 封鎖
        roles_target_id:
          expose:
            label: 角色
        permission:
          expose:
            label: 權限
      use_more_text: 更多
  page_1:
    display_title: 頁面
    display_options:
      menu:
        title: List
        description: 尋找及管理網站使用者。
      tab_options:
        title: 使用者
        description: 管理使用者帳號、角色與權限。
