label: 媒體
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 最前'
            last: '最後 »'
      fields:
        thumbnail__target_id:
          label: 縮圖
        bundle:
          label: 類型
        uid:
          label: 作者
        status:
          label: 狀態
          settings:
            format_custom_true: 已發表
            format_custom_false: 尚未發佈
        changed:
          label: 已更新
        operations:
          label: 操作
      filters:
        bundle:
          expose:
            label: 類型
        status:
          group_info:
            label: 發佈狀態
            group_items:
              1:
                title: 已發表
              2:
                title: 尚未發佈
        langcode:
          expose:
            label: 語言
      title: 媒體
      empty:
        area_text_custom:
          content: 沒有可用的內容。
  media_page_list:
    display_title: 媒體
    display_options:
      menu:
        title: 媒體
