display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 最前'
            last: '最後 »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      fields:
        title:
          label: 標題
        type:
          label: 內容類型
        name:
          label: 作者
        changed:
          label: 已更新
        operations:
          label: 操作
      filters:
        title:
          expose:
            label: 標題
        type:
          expose:
            label: 內容類型
        langcode:
          expose:
            label: 語言
