label: 誰在線上區塊
description: 顯示最近啟用的使用者姓名，以及啟用的使用者總數。
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      filters:
        access:
          expose:
            label: 最近存取時間
            description: 在使用者最近一次瀏覽網頁後多少時間內，仍被視為在線上。
      title: 誰在線上
      header:
        result:
          content: '現在共有 @total 個使用者在線上。'
      empty:
        area_text_custom:
          content: 現在沒有使用者在線上。
  who_s_online_block:
    display_title: 誰在線上
    display_options:
      block_description: 誰在線上
      display_description: 登入的使用者列表
