display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 第一頁'
            last: '最後一頁 »'
      fields:
        state:
          label: State
        label:
          label: Label
        source_language_1:
          label: 寄件人
        target_language:
          label: 收件人
        translator:
          label: 供應商
        tags_count:
          label: '標籤 (Tags)'
        changed:
          label: 已變更
        operations:
          label: Operations
      filters:
        state:
          expose:
            label: State
        source_language:
          expose:
            label: 源語言
        translator:
          expose:
            label: 供應商
  page_1:
    display_title: 頁面
