label: 最新內容
description: 最近的內容。
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 套用
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      fields:
        changed:
          separator: ', '
      title: 最新內容
      empty:
        area_text_custom:
          content: 沒有可用的內容。
      use_more_text: 更多
  block_1:
    display_title: 區塊
