label: 名詞解釋
display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: Title
        name:
          label: Author
        changed:
          label: 最近更新
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
  attachment_1:
    display_title: 附加檔案
  page_1:
    display_title: 頁面
    display_options:
      menu:
        title: 名詞解釋
