display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
        operations:
          label: Operations
      filters:
        status:
          expose:
            label: 'Published status'
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: 'Content type'
        title:
          expose:
            label: Title
  page_1:
    display_title: 頁面
