display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 第一頁'
            last: '最後一頁 »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      fields:
        created:
          label: 已建立
        label:
          label: 項目
        name:
          label: Name
      title: 訊息
      arguments:
        tjid:
          exception:
            title: All
  embed:
    display_title: 內嵌
