label: 檔案
description: 尋找和管理檔案。
display:
  default:
    display_title: Default
    display_options:
      title: 檔案
      fields:
        filename:
          label: Name
          separator: ', '
        filemime:
          label: 'MIME 型態'
        filesize:
          label: 大小
        status:
          label: Status
          settings:
            format_custom_false: 暫時
            format_custom_true: 永久
        created:
          label: 上載日期
        changed:
          label: 變更日期
        count:
          label: 使用於
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      empty:
        area_text_custom:
          content: 沒有檔案。
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'MIME 型態'
        status:
          expose:
            label: Status
  page_1:
    display_title: 檔案總覽。
    display_options:
      menu:
        title: 檔案
  page_2:
    display_options:
      fields:
        entity_label:
          label: 實體
        type:
          label: 實體類別
        count:
          label: 使用次數
          format_plural_string: !!binary MQNAY291bnQ=
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      arguments:
        fid:
          exception:
            title: All
