display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
          tags:
            previous: '‹ 上一頁'
            next: '下一頁 ›'
            first: '« 第一頁'
            last: '最後一頁 »'
      fields:
        state:
          label: State
        label:
          label: Label
        type:
          label: Type
        tags_count:
          label: '標籤 (Tags)'
        changed:
          label: 已變更
        operations:
          label: Operations
      arguments:
        tjid:
          exception:
            title: All
  checkout:
    display_title: 結帳
    display_options:
      fields:
        label:
          label: Label
        type:
          label: Type
        changed:
          label: 已變更
  submitted:
    display_title: 送出時間
