label: 內容
description: 尋找及管理內容。
display:
  default:
    display_title: Default
    display_options:
      title: 內容
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
        name:
          label: Author
        changed:
          label: Updated
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
      exposed_form:
        options:
          submit_button: 篩選
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      empty:
        area_text_custom:
          content: 沒有可用的內容。
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
  page_1:
    display_title: 頁面
    display_options:
      menu:
        title: 內容
      tab_options:
        title: 內容
        description: 尋找和管理內容
