display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: 重設
          exposed_sorts_label: 排序依據
          sort_asc_label: 遞增
          sort_desc_label: 遞減
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 每頁的項目數
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 位移
      fields:
        created:
          label: 已建立
        view_webform_submission:
          label: Operations
      arguments:
        in_draft:
          exception:
            title: All
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: 動作
        created:
          label: 已建立
        operations:
          label: Operations
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: 動作
        created:
          label: 已建立
        view_webform_submission:
          label: Operations
        edit_webform_submission:
          label: Operations
  embed_review:
    display_options:
      fields:
        created:
          label: 已建立
        view_webform_submission:
          label: Operations
