settings:
  default_reset_button_label: 重設
  default_delete_button_label: 刪除
  default_preview_next_button_label: 預覽
  default_preview_label: 預覽
  dialog_options:
    normal:
      title: 標準的
element:
  default_more_title: 更多
