title: 本網頁對您有幫助嗎？
elements: |
  was_this_page_helpful_:
    '#title': 本網頁對您有幫助嗎？
    '#options':
      'Yes': 是
      'No': 否
      'Report something wrong with this page': 舉報本網頁的錯誤。
  'yes':
    '#title': 是
  what_was_helpful_about_this_page_:
    '#title': 本網頁的哪些內容對您有幫助？
    '#description': '我們無法個別回覆所有回饋意見。如需協助，請撥打 311。'
  'no':
    '#title': 否
  what_s_wrong_with_this_page_:
    '#title': 本網頁有什麼錯誤？
    '#description': '我們無法個別回覆所有回饋意見。如需協助，請撥打 311。'
  report_something_wrong_with_this_page:
    '#title': 舉報本網頁的錯誤。
  what_s_wrong_with_this_page_feedback:
    '#title': 本網頁有什麼錯誤？
    '#description': '我們無法個別回覆所有回饋意見。如需協助，請撥打 311。'
  actions:
    '#title': 傳送回饋按鈕
    '#submit__label': 傳送回饋
settings:
  confirmation_title: 謝謝。如果想要補充任何資訊，請提供更多回饋意見。
  confirmation_message: "<p>謝謝。如果想要補充任何資訊，請提供更多回饋意見。</p>\r\n<a class=\"btn btn-primary\" href=\"/node/1168\">提供更多回饋意見</a>"
