title: Hero banner
context:
  title: Mayor's Office of Housing and Community Development
  lead: MOHCD supports residents with affordable housing opportunities and essential services to build strong communities.
variants:
- name: form
  label: "Form"
  context:
    form-title: Apply for an accessory dwelling unit permit
    percent: "30"
    title: Construction impact
    lead: false

- name: form-short
  label: "Form under 6 pages"
  context:
    form-title: Apply for an accessory dwelling unit permit
    title: Construction impact
    short: true
    lead: false
