<?php

/**
 * @file
 * Main module functions for mandrill_activity.
 */

/**
 * Return all activity on all lists for a given email address.
 *
 * @param string $email
 *   Email to load Mandrill activity for.
 *
 * @return array
 *   Array of activity.
 *
 * @throws \Exception
 */
function mandrill_activity_get_activity($email) {
  throw new \Exception('Use the getMessages() method on the API service class instead.');
}
