context:
  url: "https://sf.gov"
  image: 
    src: "/images/event-image.jpg"
    alt: "this is the alt text for the event image"
  title: "Event title"
  date: 
    month: "February"
    date: "2"
  description: "Event card description describes this event card.  Use a descriptive description."
  