name: sfgov
recipe: pantheon
config:
  framework: drupal8
  site: sfgov
  id: 91d50373-c4cf-40e4-a646-cb73e16a140c
  webroot: web
  composer_version: 1-latest
  # Note: Xdebug negatively impacts performance. It should be toggled on/off
  # using the custom tooling commands, 'lando xdebug-on' and 'lando xdebug-off',
  # as needed.
  # xdebug: develop,debug
services:
  appserver:
    run:
      - mkdir -p /var/www/logs
    overrides:
      environment:
        BEHAT_PARAMS: >-
          { "extensions": { "Behat\\MinkExtension": { "base_url":
          "http://sfgov.lndo.site", "goutte": { "guzzle_parameters": { "verify":
          false } } }, "Drupal\\DrupalExtension": { "drush": { "root":
          "/app/web" } } } }
        XDEBUG_MODE: develop,debug
        XDEBUG_SESSION_START: LANDO
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  getdb:
    description: Supplement to `lando pull` when it fails because of drush issues
    cmd:
      - appserver: rm -f /app/web/database.sql.gz
      - appserver: terminus backup:create sfgov.dev --element=db
      - appserver: terminus backup:get sfgov.dev --element=db --to=/app/web/database.sql.gz
      - database: /helpers/sql-import.sh database.sql.gz # this is relative to current working dir, be sure to run this command from `web` dir
  xdebug-on:
    service: appserver
    description: 'Enable xdebug for nginx.'
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: 'Disable xdebug for nginx.'
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
