sfgov_formio.settings:
  type: config_object
  label: 'SF.gov Form.io Settings'
  mapping:
    formio_version:
      type: string
      label: 'Form.io version'
    formio_sfds_version:
      type: string
      label: 'Form.io SFDS version'
