sfgov_formio.settings:
  type: config_object
  label: 'SF.gov Form.io Settings'
  mapping:
    formio_version:
      type: string
      label: 'Form.io version'
    formio_sfds_version:
      type: string
      label: 'Form.io SFDS version'

field.value.formio_key_value_item:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
    key:
      type: string
      label: 'Key'
    label:
      type: string
      label: 'Label'
    nested_location:
      type: string
      label: 'Nested Location'
