<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sfgov_news_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_news_form', 'node_news_edit_form'])) {
    // field_abstract is required unless field_direct_external_url is used.
    $form['field_abstract']['widget'][0]['value']['#states'] = [
      'required' => [
        ':input[data-drupal-selector="edit-field-direct-external-url-0-uri"]' => [
          'filled' => FALSE,
        ]
      ]
    ];
  }
}
