<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sfgov_news_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_news_form', 'node_news_edit_form'])) {
    // field_abstract is required unless field_direct_external_url is used.
    $form['field_abstract']['widget'][0]['value']['#states'] = [
      'required' => [
        ':input[data-drupal-selector="edit-field-direct-external-url-0-uri"]' => [
          'filled' => FALSE,
        ]
      ]
    ];
  }
}

/**
 * Implements hook_views_pre_view().
 */
function sfgov_news_views_pre_view($view) {
  // Set the pager to infinite scroll when in mobile view.
  if ($view->id() === 'news' && $view->current_display == 'page_1') {
    $md = \Drupal::service('mobile_detect');
    if ($md->isMobile()) {
      $pager = $view->display_handler->getOption('pager');
      $pager['type'] = 'infinite_scroll';
      $pager['options']['views_infinite_scroll'] = [
        'button_text' => 'Show More Results',
        'automatically_load_content' => false,
        'initially_load_all_pages' => false,
      ];
      $view->display_handler->setOption('pager', $pager);
    }
  }
}
