#!/bin/bash

set -eo pipefail

npm install @axe-core/cli -g

# get the chromedriver version compatible with this image's google chrome version
rm -rf /tmp/chromedriver
mkdir /tmp/chromedriver/
CHROMEDRIVER_VERSION="85.0.4183.87" # current google chrome version in circleci image is 85, cannot sudo to update
CHROMEDRIVER_PATH="/usr/local/bin"
wget -O /tmp/chromedriver/chromedriver.zip 'http://chromedriver.storage.googleapis.com/'$CHROMEDRIVER_VERSION'/chromedriver_linux64.zip'
unzip -o /tmp/chromedriver/chromedriver.zip chromedriver -d $CHROMEDRIVER_PATH

GI_START_URL="$MULTIDEV_SITE_URL"

if [ -n "$CIRCLE_PULL_REQUEST" ]; then
  PR='<'$CIRCLE_PULL_REQUEST'|pr>'
else
  PR='`'$CIRCLE_BRANCH'`'
fi

echo "GI_RESULT_ID from ghost inspector step: $GI_RESULT_ID"

# get the test results from result_id
SUITE_RESULTS=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/results/?apiKey=$GI_API_KEY&count=50") # max results from ghost inspector api is 50

A11Y_RESULTS_SLACK=""

# construct an object with the test id, result id, test name, and url
TESTS=$(echo $SUITE_RESULTS | jq -r '[ .data[]|{"test_id":"\(.test._id)", "result_id":"\(.suiteResult)", "test_name":"\(.test.name)", "url":"\(.urls | .[-1])", "scan_result":[]}]')

# iterate through that object, axe scan each url, and send the results to ronbot for processing
while read i; do
  echo $i | jq -r '"\(.test_id) \(.url)"'
  TEST_ID=$(echo $i | jq -r '"\(.test_id)"')
  URL=$(echo $i | jq -r '"\(.url)"')
  SCAN_JSON_DATA=$(axe --stdout $URL  --chromedriver-path "$CHROMEDRIVER_PATH/chromedriver" | jq ".[0].violations")
  URL_PATH=$(echo "/${URL#*://*/}")
  V=$(echo $SCAN_JSON_DATA | jq length)
  A11Y_RESULTS_SLACK+="$URL_PATH ($V violations)\n"
  DATA=$(printf '{
    "result_id": "%s",
    "test_id": "%s",
    "url": "%s",
    "scan_results": %s
  }' "$GI_RESULT_ID" "$TEST_ID" "$URL" "$SCAN_JSON_DATA")
  curl -s -H 'Content-Type: application/json' --data "$DATA" http://ronswanbot.herokuapp.com/webhooks/accessibility
done < <(echo $TESTS | jq -c '.[]')

# pass some things along as env variables
if [ -n "$CIRCLE_BRANCH" ]; then # circleci
  echo 'export A11Y_RESULTS_SLACK="'$A11Y_RESULTS_SLACK'"' >> $BASH_ENV
else # local
  export A11Y_RESULTS_SLACK=$A11Y_RESULTS_SLACK
fi
