display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: 'Ibalik sa pamantayan'
      fields:
        type:
          label: Uri
        timestamp:
          label: Petsa
        message:
          label: Mensahe
        link:
          label: 'Mga operasyon'
      filters:
        type:
          expose:
            label: Uri
  page:
    display_title: Pahina
