display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      fields:
        title:
          label: Pamagat
        name:
          label: 'May akda'
        changed:
          label: 'Huling binago'
  page_1:
    display_title: Pahina
