display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: Title
        status:
          label: Status
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        dropbutton:
          label: Operations
      filters:
        status:
          group_info:
            group_items:
              1:
                title: Published
        type:
          expose:
            label: Type
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        gid:
          exception:
            title: All
  page_1:
    display_title: Page
