display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
      pager:
        options:
          tags:
            previous: '‹ nakaraan'
            next: 'susunod ›'
            first: '« una'
            last: 'huli »'
      fields:
        redirect_source__path:
          label: 'Mula kay'
        created:
          label: Inilikha
  page_1:
    display_title: Page
