display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        bundle:
          label: Type
        uid:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Operations
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
      empty:
        area_text_custom:
          content: 'No content available.'
