display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      title: 'Sino ang nakakabit'
  who_s_online_block:
    display_title: 'Sino ang nakakabit'
    display_options:
      block_description: 'Sino ang nakakabit'
