display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
      fields:
        created:
          label: Inilikha
        view_webform_submission:
          label: Operations
      arguments:
        in_draft:
          exception:
            title: All
  embed_administer:
    display_options:
      fields:
        created:
          label: Inilikha
        operations:
          label: Operations
  embed_manage:
    display_options:
      fields:
        created:
          label: Inilikha
        view_webform_submission:
          label: Operations
        edit_webform_submission:
          label: Operations
  embed_review:
    display_options:
      fields:
        created:
          label: Inilikha
        view_webform_submission:
          label: Operations
