display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      filters:
        redirect_redirect__uri:
          expose:
            label: 'Para kay'
  page_1:
    display_title: Page
