label: 'Mga nilalaman na kumakailan lamang'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      title: 'Mga nilalaman na kumakailan lamang'
      empty:
        area_text_custom:
          content: 'Walang magagamit na nilalaman.'
      use_more_text: 'marami pa'
  block_1:
    display_title: Tipak
