display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
      fields:
        path:
          label: Landas
  page_1:
    display_title: Page
