label: 'Mga tao'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        name:
          label: Bansag
        status:
          label: Status
          settings:
            format_custom_true: Aktibo
            format_custom_false: Hinadlangan
        roles_target_id:
          label: Roles
        created:
          label: 'Kasapi nang'
        operations:
          label: Operations
      filters:
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Aktibo
              2:
                title: Hinadlangan
      title: 'Mga tao'
      use_more_text: 'marami pa'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Listahan
      tab_options:
        title: 'Mga tao'
