display:
  default:
    display_title: Default
    display_options:
      fields:
        changed:
          label: Updated
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
  page_1:
    display_title: Page
