display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: Title
        name:
          label: Author
        changed:
          label: 'Huling binago'
  page_1:
    display_title: Page
