display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        title:
          label: Title
        name:
          label: Author
        changed:
          label: Updated
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        langcode:
          expose:
            label: Language
