label: 'Mga nilalaman na kumakailan lamang'
display:
  default:
    display_title: Default
    display_options:
      title: 'Mga nilalaman na kumakailan lamang'
      exposed_form:
        options:
          reset_button_label: Reset
      empty:
        area_text_custom:
          content: 'No content available.'
      use_more_text: 'marami pa'
  block_1:
    display_title: Tipak
