display:
  default:
    display_title: Default
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
  block_1:
    display_title: Tipak
  page_1:
    display_title: Page
