display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        type:
          label: Type
        tags_count:
          label: 'Mga etiketa'
        operations:
          label: Operations
      arguments:
        tjid:
          exception:
            title: All
  checkout:
    display_options:
      fields:
        type:
          label: Type
