display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
      pager:
        options:
          tags:
            previous: '‹ nakaraan'
            next: 'susunod ›'
            first: '« una'
            last: 'huli »'
      fields:
        created:
          label: Inilikha
        name:
          label: Name
      arguments:
        tjid:
          exception:
            title: All
