display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        title:
          label: Title
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
  overview:
    display_options:
      tab_options:
        title: Content
  user_page:
    display_options:
      tab_options:
        title: Content
      arguments:
        uid:
          exception:
            title: All
