display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        name:
          label: Pangalan
      arguments:
        tjid:
          exception:
            title: All
