display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        changed:
          label: Updated
        operations:
          label: Operations
  page_1:
    display_title: Page
