label: 'Sino ang bago'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      title: 'Sino ang bago'
  block_1:
    display_title: 'Sino ang bago'
    display_options:
      block_description: 'Sino ang bago'
