label: 'Mga talaksan'
display:
  default:
    display_title: Default
    display_options:
      title: 'Mga talaksan'
      fields:
        filename:
          label: Name
        status:
          label: Status
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
      filters:
        status:
          expose:
            label: Status
  page_1:
    display_options:
      menu:
        title: 'Mga talaksan'
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: All
