display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        group_roles:
          label: Roles
        changed:
          label: Updated
        dropbutton:
          label: Operations
      arguments:
        gid:
          exception:
            title: All
  page_1:
    display_title: Page
