display:
  default:
    display_title: Default
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
      arguments:
        tid:
          exception:
            title: All
  page_1:
    display_title: Page
