label: Nilalaman
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: 'Ibalik sa pamantayan'
      fields:
        title:
          label: Pamagat
        name:
          label: 'May akda'
        status:
          label: Kalagayan
          settings:
            format_custom_true: Inilathala
        changed:
          label: Nabago
        operations:
          label: 'Mga operasyon'
      filters:
        title:
          expose:
            label: Pamagat
        status:
          expose:
            label: Kalagayan
          group_info:
            group_items:
              1:
                title: Inilathala
        langcode:
          expose:
            label: Wika
      title: Nilalaman
      empty:
        area_text_custom:
          content: 'Walang magagamit na nilalaman.'
  page_1:
    display_options:
      menu:
        title: Nilalaman
      tab_options:
        title: Nilalaman
    display_title: Pahina
