display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        type:
          label: Type
        timestamp:
          label: Petsa
        message:
          label: Mensahe
        link:
          label: Operations
      filters:
        type:
          expose:
            label: Type
  page:
    display_title: Page
