display:
  default:
    display_title: Default
    display_options:
      fields:
        bundle:
          label: Type
        uid:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
