display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        type:
          label: Type
        source_language:
          label: 'Mula kay'
        target_language:
          label: To
        tags_count:
          label: Tags
        operations:
          label: Operations
  page_1:
    display_title: Page
