display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: 'Ibalik sa pamantayan'
      fields:
        bundle:
          label: Uri
        uid:
          label: 'May akda'
        status:
          label: Kalagayan
          settings:
            format_custom_true: Inilathala
        changed:
          label: Nabago
        operations:
          label: 'Mga operasyon'
      filters:
        bundle:
          expose:
            label: Uri
        status:
          group_info:
            group_items:
              1:
                title: Inilathala
        langcode:
          expose:
            label: Wika
      empty:
        area_text_custom:
          content: 'Walang magagamit na nilalaman.'
