display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        target_language:
          label: 'Para kay'
        tags_count:
          label: 'Mga etiketa'
        operations:
          label: Operations
  page_1:
    display_title: Page
