label: 'Mga talaksan'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Salain
          reset_button_label: Reset
      fields:
        filename:
          label: Pangalan
        status:
          label: Status
      filters:
        status:
          expose:
            label: Status
      title: 'Mga talaksan'
  page_1:
    display_options:
      menu:
        title: 'Mga talaksan'
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: All
