display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: Title
        name:
          label: Author
        changed:
          label: 'Huling binago'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
  page_1:
    display_title: Page
