label: 'Mga punang kumakailan lamang'
display:
  default:
    display_options:
      title: 'Mga punang kumakailan lamang'
      empty:
        area_text_custom:
          content: 'Walang magagamit na mga puna.'
  block_1:
    display_title: Tipak
    display_options:
      block_description: 'Mga punang kumakailan lamang'
