title: 'Nakatulong ba ang page na ito?'
elements: |
  was_this_page_helpful_:
    '#title': 'Nakatulong ba ang page na ito?'
    '#options':
      'Yes': Oo
      'No': Hindi
      'Report something wrong with this page': 'Mag-ulat ng anumang mali sa page na ito.'
  'yes':
    '#title': Oo
  what_was_helpful_about_this_page_:
    '#title': 'Ano ang nakatulong sa iyo sa page na ito?'
    '#description': 'Hindi namin masasagot ang bawat isang feedback. Kung kailangan mo ng tulong, tumawag sa 311.'
  'no':
    '#title': Hindi
  what_s_wrong_with_this_page_:
    '#title': 'Ano ang mali sa page na ito?'
    '#description': 'Hindi namin masasagot ang bawat isang feedback. Kung kailangan mo ng tulong, tumawag sa 311.'
  report_something_wrong_with_this_page:
    '#title': 'Mag-ulat ng anumang mali sa page na ito.'
  what_s_wrong_with_this_page_feedback:
    '#title': 'Ano ang mali sa page na ito?'
    '#description': 'Hindi namin masasagot ang bawat isang feedback. Kung kailangan mo ng tulong, tumawag sa 311.'
  actions:
    '#submit__label': 'Magpadala ng feedback'
settings:
  confirmation_title: 'Salamat. Kung mayroon kang anumang idaragdag, magbigay sa amin ng higit pang feedback.'
  confirmation_message: "<p>Salamat. Kung mayroon kang anumang idaragdag, magbigay sa amin ng higit pang feedback.</p>\r\n<a class=\"btn btn-primary\" href=\"/node/1168\">Bigyan pa kami ng feedback</a>"
