<?php

/**
 * @file
 * Contains sfgov_alerts.module.
 */

/**
 * Implements hook_theme().
 */
function sfgov_alerts_theme() {
  return [
    'sfgov_alerts' => [
      'render element' => 'content',
    ],
  ];
}

function sfgov_alerts_node_presave($node) {
  $type = $node->getType();
  if ($type == 'department') {

    $alert_expiration_original = $node->original->field_alert_expiration_date->value;
    $alert_expiration_updated = $node->field_alert_expiration_date->value;

    $alert_text_updated = $node->field_alert_text->value;

    if ($alert_expiration_original != $alert_expiration_updated) {

      $log_message = t('@expiration - @text', [
        '@text' => strip_tags($alert_text_updated),
        '@expiration' => $alert_expiration_updated,
      ]);

      $display_message = t('Alert Expiration Date: @expiration. Alert Text: @text', [
        '@text' => strip_tags($alert_text_updated),
        '@expiration' => $alert_expiration_updated
      ]);

      Drupal::logger('sfgov_alerts')->info($log_message);
      Drupal::messenger()->addMessage($display_message);
    }
  }
}
