label: Hero
status: ready

context:
  hero:
    callout: 'Hero callout:'
    title: Call attention to a current priority
    paragraph: Support the callout with some short explanatory text. You don't need more than a couple of sentences.
    button:
      text: Learn about what we do
      href: 'javascript:void(0)'
