#!/bin/bash

set -eo pipefail

npm install @axe-core/cli -g

GI_START_URL="$MULTIDEV_SITE_URL"

if [ -n "$CIRCLE_PULL_REQUEST" ]; then
  PR='<'$CIRCLE_PULL_REQUEST'|pr>'
else
  PR='`'$CIRCLE_BRANCH'`'
fi

echo "GI_RESULT_ID from ghost inspector step: $GI_RESULT_ID"

# get the test results from result_id
SUITE_RESULTS=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/results/?apiKey=$GI_API_KEY&count=50") # max results from ghost inspector api is 50

A11Y_RESULTS_SLACK=""

# construct an object with the test id, result id, test name, and url
TESTS=$(echo $SUITE_RESULTS | jq -r '[ .data[]|{"test_id":"\(.test._id)", "result_id":"\(.suiteResult)", "test_name":"\(.test.name)", "url":"\(.urls | .[-1])", "scan_result":[]}]')

# iterate through that object, axe scan each url, and send the results to ronbot for processing
while read i; do
  echo $i | jq -r '"\(.test_id) \(.url)"'
  TEST_ID=$(echo $i | jq -r '"\(.test_id)"')
  URL=$(echo $i | jq -r '"\(.url)"')
  SCAN_JSON_DATA=$(axe --stdout $URL | jq ".[0].violations")
  SCAN_RESULT=$?
  if [ $SCAN_RESULT -ne 0 ]; then
    V="scan error"
  else
    V=$(echo $SCAN_JSON_DATA | jq length)" violations"
  fi
  URL_PATH=$(echo "/${URL#*://*/}")
  A11Y_RESULTS_SLACK+="$URL_PATH ($V)\n"
  DATA=$(printf '{
    "result_id": "%s",
    "test_id": "%s",
    "url": "%s",
    "scan_results": %s
  }' "$GI_RESULT_ID" "$TEST_ID" "$URL" "$SCAN_JSON_DATA")
  curl -s -H 'Content-Type: application/json' --data "$DATA" http://ronswanbot.herokuapp.com/webhooks/accessibility
done < <(echo $TESTS | jq -c '.[]')

# pass some things along as env variables
if [ -n "$CIRCLE_BRANCH" ]; then # circleci
  echo 'export A11Y_RESULTS_SLACK="'$A11Y_RESULTS_SLACK'"' >> $BASH_ENV
else # local
  export A11Y_RESULTS_SLACK=$A11Y_RESULTS_SLACK
fi
