<?php

/**
 * @file
 * This is the External Links module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_modules_installed().
 */
function extlink_modules_installed($modules) {
  if (in_array('extlink', $modules)) {
    // Be friendly to your users: what to do after install?
    $url = Url::fromRoute('extlink_admin.settings');
    if (PHP_SAPI != 'cli') {
      drupal_set_message(t('You can now <a href="@extlink_admin">configure the External Links module</a> for your site.',
        ['@extlink_admin' => $url->toString()]), 'status');
    }
  }
}

/**
 * Implements hook_help().
 */
function extlink_help($route_name, RouteMatchInterface $arg) {
  switch ($route_name) {
    case 'help.page.extlink':
      $output = '';
      $output .= '<p>' . t('External Links is used to differentiate between internal and external links. Using jQuery, it will find all external links on a page and add an external icon indicating it will take you offsite or a mail icon for mailto links.') . '</p>';
      return ['#markup' => $output];
  }
}

/**
 * Implements hook_page_attachments().
 */
function extlink_page_attachments(array &$attachments) {
  $config = \Drupal::config('extlink.settings');
  $attachments['#attached']['library'][] = 'extlink/drupal.extlink';

  // Allow other modules to alter the excluded CSS selector settings.
  $cssExclude = $config->get('extlink_css_exclude');
  \Drupal::moduleHandler()->alter('extlink_css_exclude', $cssExclude);

  $attachments['#attached']['drupalSettings']['data']['extlink'] = [
    'extTarget'           => $config->get('extlink_target'),
    'extTargetNoOverride' => $config->get('extlink_target_no_override'),
    'extNofollow'         => $config->get('extlink_nofollow', 0),
    'extFollowNoOverride' => $config->get('extlink_follow_no_override', 0),
    'extClass'            => $config->get('extlink_class'),
    'extLabel'            => Html::escape($config->get('extlink_label')),
    'extImgClass'         => $config->get('extlink_img_class'),
    'extSubdomains'       => $config->get('extlink_subdomains'),
    'extExclude'          => $config->get('extlink_exclude'),
    'extInclude'          => $config->get('extlink_include'),
    'extCssExclude'       => $cssExclude,
    'extCssExplicit'      => $config->get('extlink_css_explicit'),
    'extAlert'            => $config->get('extlink_alert'),
    'extAlertText'        => $config->get('extlink_alert_text'),
    'mailtoClass'         => $config->get('extlink_mailto_class'),
    'mailtoLabel'         => Html::escape($config->get('extlink_mailto_label')),
  ];
}
