<?php

/**
 * @file
 * Contains custom_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migration_plugins_alter().
 */
function sfgov_change_content_type_migration_plugins_alter(&$definitions) {

}

/**
 * Implements hook_migrate_MIGRATE_ID_prepare_alter().
 */
function sfgov_change_content_type_migrate_convert_public_body_to_agency_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

}
