<?php
/**
 * ListenerAuthEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Drupal\tmgmt_contentapi\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Lionbridge Content API
 *
 * Enable translations with the Lionbridge Content API.
 *
 * OpenAPI spec version: 1.4.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Drupal\tmgmt_contentapi\Swagger\Client\Model;


/**
 * ListenerAuthEnum Class Doc Comment
 *
 * @category Class
 * @description Authentication type for listener, if left empty then CTT_GENERATED_TOKEN will be used.
 * @package  Drupal\tmgmt_contentapi\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListenerAuthEnum
{
    /**
     * Possible values of this enum
     */
    const CTT_GENERATED_TOKEN = 'CTT_GENERATED_TOKEN';
    const NONE = 'NONE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CTT_GENERATED_TOKEN,
            self::NONE,
        ];
    }
}


