mandrill_template.mandrill_template_map.*:
  type: config_entity
  label: 'Mandrill Template Map config'
  mapping:
    id:
      type: string
      label: 'Machine Name'
    label:
      type: string
      label: 'Label'
    mailsystem_key:
      type: string
      label: 'MailSystem Key'
    template_id:
      type: string
      label: 'Template ID'
    main_section:
      type: string
      label: 'Main Template Section'
    sections:
      type: string
      label: 'Template Sections'
