label: Dropdown
context:
  title: Type of construction
  options:
    - title: "I-A: Fire Resistive Non-Combustible"
    - title: "I-B: Fire Resistive Non-Combustible"
    - title: "II-A: Protected Non-Combustible"
    - title: "II-B: Unprotected Non-Combustible"
    - title: "III-A: Protected Combustible"
    - title: "III-B: Unprotected Combustible"
    - title: "IV: Heavy Timber"
    - title: "V-A: Protected Wood Frame"
    - title: "V-B: Unprotected Wood Frame"
