id: d7_advagg_css_minify_settings
label: 'AdvAgg CSS Minify configuration'
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - advagg_css_compressor
process:
  minifier: advagg_css_compressor
destination:
  plugin: config
  config_name: advagg_css_minify.settings
