<?php
//
///**
// * @file
// * Theme functions for Hops.
// */
//
///**
// * Get theme functionalities.
// */
//function hops_get_theme(&$variables) {
//  hops_add_libraries($variables);
//}
//
///**
// * Add libraries.
// */
//function hops_add_libraries(&$variables) {
//  $typekit_id = theme_get_setting('typekit_id');
//  if (!empty($typekit_id)) {
//    $variables['typekit_id'] = theme_get_setting('typekit_id');
//  }
//}
