label: Radio buttons
context:
  id: billing_contact
  title: Who should we contact to pay application fees?
  options:
  - title: The owner
    index: 1

  - title: The application contact
    index: 2

  - title: Someone else
    index: 3
