<?php

/**
 * @file
 * Contains sfgov_qless.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_qless_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route == 'sfgov_qless.qless_controller_display_page') {
    $variables['attributes']['class'][] = 'page-sfgov-qless';
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_qless_theme() {
  return [
    'qless' => [
      'variables' => [
        'results' => NULL,
        'api_data' => NULL,
      ],
    ],
  ];
}
