<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function sfgov_resource_collection_node_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  if ($entity->isNew() && $entity->bundle() == 'resource_collection') {
    $storage = \Drupal::entityTypeManager()->getStorage('paragraph');
    $langcode = $form_state->get('langcode');

    // Append items into Custom Sections.
    foreach ([
      'Documents',
      'Data',
      'Resources'
    ] as $title) {
      $paragraphs_entity = $storage->create([
        'type' => 'section',
        'langcode' => $langcode,
        'field_title' => $title,
      ]);
      $entity->get('field_content')->appendItem($paragraphs_entity);
    }
  }
}
