<?php
/**
 * @file
 * Theme hooks for SFGOV.
 */

// Include all files from the includes directory.
$includes_path = dirname(__FILE__) . '/includes/*.inc';
foreach (glob($includes_path) as $filename) {
  require_once dirname(__FILE__) . '/includes/' . basename($filename);
}

$module_handler = Drupal::service('module_handler');
$devel_path = $module_handler->getModule('devel')->getPath();
require_once($devel_path.'/kint/kint/Kint.class.php');
Kint::$maxLevels = 4;