id: d7_advagg_old_ie_compatibility_settings
label: 'AdvAgg Old IE Compatibility configuration'
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - advagg_ie_css_selector_limiter
    - advagg_ie_css_selector_limiter_value
process:
  active: advagg_ie_css_selector_limiter
  limit: advagg_ie_css_selector_limiter_value
destination:
  plugin: config
  config_name: advagg_old_ie_compatibility.settings
