label: Text field
context:
  title: Name of your organization
  id: org-name
variants:
  - name: with-help-text
    label: "With help text"
    context:
      help-text: Please avoid abbreviations or acronyms.
