<?php

/**
 * @file
 * Contains sfgov_video.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function sfgov_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sfgov_video module.
    case 'help.page.sfgov_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Video paragraph and transcript page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_video_theme() {
  return [
    'sfgov_video_page' => [
      'variables' => [
        'title' => '',
        'body' => []
      ]
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function sfgov_video_paragraph_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'video') {
    $video_previous = !$entity->isNew() ? $entity->original->field_video->value : NULL;
    $video_current = $entity->field_video->value;

    // If the vide is updated.
    if ($video_previous != $video_current) {
      /** @var \Drupal\sfgov_video\VideoService $video_service */
      $video_service = \Drupal::service('sfgov_video.utilities');
      $video_id = $video_service->getVideoId($video_current);
      $transcript = $video_service->getYoutubeTranscript($video_id);

      // If there is a transcript for the given video.
      if ($transcript) {
        // Convert array into plain text.
        $transcript_plain = '';
        foreach ($transcript as $value) {
          $transcript_plain .= "<p>" . $value['text'] . "</p>";
        }

        // Set the transcript as value for field_text.
        $entity->field_text = $transcript_plain;
        $entity->field_text->format = 'sf_restricted_html';
      }
    }
  }
}
