<?php

/**
 * @file
 * Contains sfgov_video.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function sfgov_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sfgov_video module.
    case 'help.page.sfgov_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Video paragraph and transcript page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_video_theme() {
  return [
    'sfgov_video_page' => [
      'variables' => [
        'title' => '',
        'body' => []
      ]
    ],
  ];
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function sfgov_video_field_widget_paragraphs_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  $field_definition = $context['items']->getFieldDefinition();
  $paragraph_entity_reference_field_name = $field_definition->getName();

  if ($paragraph_entity_reference_field_name == 'field_contents') {
    /** @see \Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget::formElement() */
    $widget_state = \Drupal\Core\Field\WidgetBase::getWidgetState($element['#field_parents'], $paragraph_entity_reference_field_name, $form_state);

    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph_instance = $widget_state['paragraphs'][$element['#delta']]['entity'];
    $paragraph_type = $paragraph_instance->bundle();

    // Add a disclaimer message about the video transcript workflow.
    if ($paragraph_type == 'video') {
      if (isset($element['subform']['field_text'])) {
        $element['subform']['field_text_help'] = [
          '#type' => 'container',
          '#title' => t('Video transcript'),
          '#prefix' => '<div class="messages messages--warning">',
          '#suffix' => '</div>',
          '#weight' => 3,
          '#markup' => t('When you add a new video and save this page, the transcript will be automatically imported from Youtube. After it is imported, you can edit the transcript.'),
        ];
      }
    }
  }
}


/**
 * Implements hook_ENTITY_TYPE_update().
 */
function sfgov_video_paragraph_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'video') {
    $video_previous = !$entity->isNew() ? $entity->original->field_video->value : NULL;
    $video_current = $entity->field_video->value;

    // If the vide is updated.
    if ($video_previous != $video_current) {
      /** @var \Drupal\sfgov_video\VideoService $video_service */
      $video_service = \Drupal::service('sfgov_video.utilities');
      $video_id = $video_service->getVideoId($video_current);
      $transcript = $video_service->getYoutubeTranscript($video_id);

      // If there is a transcript for the given video.
      if ($transcript) {
        // Convert array into plain text.
        $transcript_plain = '';
        foreach ($transcript as $value) {
          $transcript_plain .= "<p>" . $value['text'] . "</p>";
        }

        // Set the transcript as value for field_text.
        $entity->set('field_text', [
          'value' => $transcript_plain,
          'format' => 'sf_restricted_html',
        ]);
      }
    }
  }
}
