#!/bin/bash

set -eo pipefail

# use the terminus env vars created by previous steps
GI_START_URL="$MULTIDEV_SITE_URL/"

echo "Using start url: $GI_START_URL"

# set up a couple variables to monitor result state
STATUS='null'
SUITE_RESULT=
PASSING=

EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE/execute?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1"

echo "Execute url: $EXECUTE_URL"

RESULT_ID=$(curl -s $EXECUTE_URL | jq -r '.data._id')

# Poll for the suite result, sleep for a few seconds if it hasn't changed
echo "Polling for suite results (ID: $RESULT_ID)"
while [ "$STATUS" = 'null' ]; do
  SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$RESULT_ID/?apiKey=$GI_API_KEY")
  RESPONSE_STATUS=$(echo $SUITE_RESULT | jq -r '.code')
  if [ $? -ne 0 ] || [ "$RESPONSE_STATUS" == 'ERROR' ]; then # invalid json or api error, break
    echo "API ERROR"
    break
  fi
  STATUS=$(echo $SUITE_RESULT | jq -r '.data.passing')
  echo " - status: $STATUS"
  sleep 5
done

# status has been updated, check results for "passing"
if [ "$(echo $SUITE_RESULT | jq -r '.data.passing')" != 'true' ]; then
  echo "Suite failed! ¯\_(ツ)_/¯"
  PASSING=1
else 
  echo "Suite passed! \o/"
  PASSING=0
fi

# output suite tests with results
SUITE_TESTS=$(curl -s "https://api.ghostinspector.com/v1/suites/$GI_SUITE/tests/?apiKey=$GI_API_KEY")
echo $SUITE_TESTS | jq -r '.data[] | if(.passing) then "\(.name): passed" else "\(.name): failed" end'

# return our passing status
exit $PASSING
