#!/bin/bash

set -eo pipefail

# use the terminus env vars created by previous steps
GI_START_URL=https://$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/

echo "Using start url: $GI_START_URL"

# set up a couple variables to monitor result state
STATUS='null'
SUITE_RESULT=
PASSING=

EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE/execute?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1"

echo "Execute url: $EXECUTE_URL"