field.field.*.*.*.third_party.telephone_validation:
  type: mapping
  label: 'Extra settings for validation'
  mapping:
    format:
      type: integer
      label: Format
    country:
      type: sequence
      label: 'Countries'
      sequence:
        type: string
        label: 'Country'
    allow_emergency:
      type: boolean
      label: Allow Emergency
    allow_short:
      type: boolean
      label: Allow Short
