label: Traducción
tips:
  locale-overview:
    label: 'Traducción de la interfaz de usuario'
    body: 'Esta página le permite traducir la interfaz de usuario o modificar traducciones existentes. Si ha instalado su sitio web inicialmente en inglés, primero debe añadir otro idioma en la <a href="[site:url]admin/config/regional/language">página de Idiomas</a>, para poder usar esta página.'
  locale-language:
    label: 'Translation language'
    body: 'Elija el idioma que quiere traducir.'
  locale-search:
    label: Buscar
    body: 'Intruduzca la palabra u oración específica que usted desea traducir, también puede escribir solamente una parte de la palabra.'
  locale-filter:
    label: 'Filtrar la búsqueda'
    body: 'Puede buscar cadenas no traducidas si quiere traducir algo que todavía no está traducido. Si quiere modificar una traducción exitente, podría querer buscar solo cadenas traducidas.'
  locale-submit:
    label: 'Aplicar su criterio de búsqueda'
    body: 'Para aplicar su criterio de búsqueda, haga click en el botón <em>Filtrar</em>.'
  locale-translate:
    label: Traducir
    body: 'Puede escribir su propia traducción en los campos de texto en la columna de la derecha. Intente fijarse en cual contexto el texto será usado para traducirlo de la manera apropiada.'
  locale-validate:
    label: 'Validar la traducción'
    body: 'Cuando haya terminado sus traducciones, haga clic en el botón <em>Guardar traducciones</em>. Usted debe guardar sus traducciones, cada vez antes de cambiar de página o hacer una nueva búsqueda.'
  locale-continue:
    label: Continuando
    body: 'Las traducciones que usted haya hecho aquí se utilizarán en la interfaz de usuario de su sitio web. Si quiere utilizarlas en otro sitio o modificarlas en un editor de traducciones externo, puede <a href="[site:url]admin/config/regional/translate/export">exportarlas</a> a un archivo .po e <a href="[site:url]admin/config/regional/translate/import">importarlas</a> después.'
