display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
            format_custom_false: 'No publicado'
        changed:
          label: Actualizado
        dropbutton:
          label: Operaciones
      filters:
        status:
          expose:
            label: 'Estado de publicación'
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'No publicado'
        type:
          expose:
            label: Tipo
      empty:
        area_text_custom:
          content: 'No hay contenido disponible.'
      arguments:
        gid:
          exception:
            title: Todo
  page_1:
    display_title: Página
