label: 'Término de taxonomía'
description: 'Contenido perteneciente a determinado término de taxonomía.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      arguments:
        tid:
          exception:
            title: Todo
  feed_1:
    display_title: Agregador
  page_1:
    display_title: Página
