display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
        operations:
          label: Operaciones
      filters:
        status:
          expose:
            label: 'Estado de publicación'
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'No publicado'
        type:
          expose:
            label: 'Tipo de contenido'
        title:
          expose:
            label: Título
  page_1:
    display_title: Página
