display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      fields:
        node_bulk_form:
          action_title: Acción
        title:
          label: Título
        name:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
            format_custom_false: 'No publicado'
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'No publicado'
        langcode:
          expose:
            label: Idioma
    display_title: Máster
  overview:
    display_options:
      tab_options:
        title: Contenido
  user_page:
    display_options:
      tab_options:
        title: Contenido
      arguments:
        uid:
          exception:
            title: Todo
