display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        state:
          label: State
        label:
          label: Label
        type:
          label: Tipo
        tags_count:
          label: Etiquetas
        operations:
          label: Operaciones
      arguments:
        tjid:
          exception:
            title: Todo
  checkout:
    display_options:
      fields:
        label:
          label: Label
        type:
          label: Tipo
