display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'último »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        created:
          label: Creado
        label:
          label: Elemento
        name:
          label: Name
      title: Mensajes
      arguments:
        tjid:
          exception:
            title: All
  embed:
    display_title: Incrustar
