display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        state:
          label: State
        label:
          label: Label
        type:
          label: Type
        source_language:
          label: Desde
          separator: ', '
        target_language:
          label: To
          separator: ', '
        progress:
          label: Progreso
        word_count:
          label: Palabra
          separator: ', '
        tags_count:
          label: Tags
          separator: ', '
        changed:
          label: Modificado
          separator: ', '
        operations:
          label: Operations
      filters:
        state:
          expose:
            label: Estados
          group_info:
            label: State
        source_language:
          expose:
            label: 'Idioma de origen'
        job_type:
          group_info:
            label: 'Tipo de empleo'
  page_1:
    display_title: Page
