label: Archivos
description: 'Encontrar y administrar archivos.'
display:
  default:
    display_title: Default
    display_options:
      title: Archivos
      fields:
        filename:
          label: Name
          separator: ', '
        filemime:
          label: 'Tipo MIME'
        filesize:
          label: Tamaño
        status:
          label: Status
          settings:
            format_custom_false: Temporal
            format_custom_true: Permanente
        created:
          label: 'Fecha de subida'
        changed:
          label: 'Fecha del último cambio'
        count:
          label: 'Usado en'
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No hay archivos disponibles.'
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'Tipo MIME'
        status:
          expose:
            label: Status
  page_1:
    display_title: 'Vista general de archivos'
    display_options:
      menu:
        title: Archivos
  page_2:
    display_title: 'Usos del archivo'
    display_options:
      title: 'Usos del archivo'
      fields:
        entity_label:
          label: Entidad
        type:
          label: 'Tipo de entidad'
        module:
          label: 'Registrando módulo'
        count:
          label: 'Conteo de usos'
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      arguments:
        fid:
          exception:
            title: All
          title: 'Información de uso del fichero para {{ arguments.fid }}'
