label: 'Contenido reciente'
description: 'Contenido reciente.'
display:
  default:
    display_title: Default
    display_options:
      title: 'Contenido reciente'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      empty:
        area_text_custom:
          content: 'No hay contenido disponible.'
      use_more_text: Más
  block_1:
    display_title: Bloque
