label: 'Miembros del grupo'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        name:
          label: Usuario
          separator: ', '
        group_roles:
          label: Roles
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        created:
          label: 'se unió'
          separator: ', '
        edit_group_content:
          text: 'Editar miembro'
        delete_group_content:
          text: 'Eliminar el miembro'
        dropbutton:
          label: Operations
      arguments:
        gid:
          exception:
            title: All
      title: Miembros
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Miembros
