display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        filename:
          separator: ', '
        fid:
          separator: ', '
  page_1:
    display_options:
      menu:
        title: List
      fields:
        filename:
          separator: ', '
        fid:
          separator: ', '
        filename_1:
          label: Filename
          separator: ', '
  page_2:
    display_options:
      fields:
        filename:
          separator: ', '
        fid:
          separator: ', '
