settings:
  default_reset_button_label: Reset
  default_delete_button_label: Eliminar
  default_preview_next_button_label: Previsualizar
  default_preview_label: Previsualizar
element:
  default_more_title: Más
