title: '¿Le ha resultado útil esta página?'
elements: |
  was_this_page_helpful_:
    '#title': '¿Le ha resultado útil esta página?'
    '#options':
      'Yes': Sí
      'Report something wrong with this page': 'Informe de algún error en esta página.'
  'yes':
    '#title': Sí
  what_was_helpful_about_this_page_:
    '#title': '¿Qué le ha parecido útil de esta página?'
    '#description': 'No podemos responder individualmente a todos los comentarios. Si necesita ayuda, llame al 311.'
  what_s_wrong_with_this_page_:
    '#title': '¿Hay algún error en esta página?'
    '#description': 'No podemos responder individualmente a todos los comentarios. Si necesita ayuda, llame al 311.'
  report_something_wrong_with_this_page:
    '#title': 'Informe de algún error en esta página.'
  what_s_wrong_with_this_page_feedback:
    '#title': '¿Hay algún error en esta página?'
    '#description': 'No podemos responder individualmente a todos los comentarios. Si necesita ayuda, llame al 311.'
  actions:
    '#submit__label': 'Envíe su comentario'
settings:
  confirmation_title: 'Gracias. Si tiene algo más que añadir, envíenos más comentarios.'
  confirmation_message: "<p>Gracias. Si tiene algo más que añadir, envíenos más comentarios.</p>\r\n<a class=\"btn btn-primary\" href=\"/node/1168\">Envíenos más comentarios</a>"
