<?php

use \Drupal\Core\Form\FormStateInterface;
use \Symfony\Component\HttpFoundation\RedirectResposne;


// $module_handler = Drupal::service('module_handler');
// $devel_path = $module_handler->getModule('devel')->getPath();
// require_once($devel_path.'/kint/kint/Kint.class.php');
// Kint::$maxLevels = 4;


function sfgov_utilities_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Kint::dump($form);
  $viewFormId = $form['#id'];
  error_log('search view form id: ' . $viewFormId);
  if($viewFormId == 'views-exposed-form-search-page-1') {
    // foreach (array_keys($form['actions']) as $action) {
    //   if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
    //     $form['actions'][$action]['#submit'][] = 'sfgov_utilities_search_form_submit';
    //   }
    // }
    // $keyword = $form_state->getValues()['keyword'];
    // Kint::dump($keyword);
    /*
    $form['#attached']['library'][] = 'sfgov_search/search';
    $form['#action'] = \Drupal\Core\Url::fromRoute('sfgov_search.content')->toString();
    */
  }
}

function sfgov_utilities_search_form_submit(array $form, FormStateInterface $form_state) {
  // Kint::dump($form_state->getValues());
  $keyword = $form_state->getValues()['keyword'];
  error_log('search form submit keyword: ' . $keyword);
  // Kint::dump($keyword);
  // $url = \Drupal\Core\Url::fromRoute('sfgov_search.content', ['keyword' => $keyword]);
  // error_log($url->toString());
  // $form_state->setRedirectUrl(\Drupal\Core\Url::fromUri('http://google.com'));
  // $form_state->setRedirect('sfgov_search.content', ['keyword' => 'what']);
  // $redirect = new RedirectResponse('http://google.com');
  // $redirect->send();
}