# Schema for the views plugins of the tmgmt_local module.

views.field.tmgmt_local_item_count:
  type: views_field
  label: 'Item count'
  mapping:
    state:
      type: string
      label: 'State'

views.field.tmgmt_local_loopcount:
  type: views_field
  label: 'Loop count'

views.field.tmgmt_local_progress:
  type: views_field
  label: 'Progress'

views.field.tmgmt_local_task_item_operations:
  type: views_field
  label: 'Task item operations'

views.field.tmgmt_local_task_status:
  type: views.field.numeric
  label: 'Task status'

views.field.tmgmt_local_task_item_status:
  type: views.field.numeric
  label: 'Task item status'

views.field.tmgmt_local_task_operations:
  type: views_field
  label: 'Task operations'

views.field.tmgmt_local_wordcount:
  type: views_field
  label: 'Word count'

views.filter.tmgmt_local_task_eligible:
  type: views_filter
  label: 'Eligible'

# @todo remove when this core issue is fixed #2637690
views.filter_value.user_current:
  type: boolean
  label: 'Current user value'
