#!/bin/bash

set -eo pipefail

#
# This script starts up the test process.
#
# - Environment settings (e.g. git config) are initialized
# - Terminus plugins are installed
# - Any needed code updates are done
#

DEVELOP_BRANCH="pr-863"

# if this is the develop branch, set the TERMINUS_ENV to preview
if [[ $CIRCLE_BRANCH == $DEVELOP_BRANCH ]] ; then
  echo 'export DEFAULT_ENV="'$DEVELOP_BRANCH'"' >> $BASH_ENV
  echo 'export TERMINUS_ENV="'$DEVELOP_BRANCH'"' >> $BASH_ENV
fi

echo "Begin build for $DEFAULT_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Delete leftover CI environments
terminus -n build:env:delete:ci "$TERMINUS_SITE" --keep=2 --yes
