_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  amplitude: 0
  anonymous_redirect: 0
  automated_cron: 0
  basic_auth: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  bulk_update_fields: 0
  cache_control_override: 0
  cer: 0
  ckeditor: 0
  components: 0
  config: 0
  config_direct_save: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  content_lock: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  entity_reference_unpublished: 0
  exif_orientation: 0
  fancy_file_delete: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_delete: 0
  filter: 0
  fixed_block_content: 0
  google_analytics_reports: 0
  google_analytics_reports_api: 0
  google_tag: 0
  gtranslate: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  job_scheduler: 0
  key: 0
  language: 0
  link: 0
  linkit: 0
  locale: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_entity_file_replace: 0
  media_revisions_ui: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  mimemail: 0
  node: 0
  node_edit_protection: 0
  office_hours: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  protected_pages: 0
  public_preview: 0
  quick_node_clone: 0
  redirect: 0
  rest: 0
  rest_views: 0
  rest_views_revisions: 0
  restui: 0
  role_delegation: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search_api: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_api_solr_legacy: 0
  sendgrid_integration: 0
  serialization: 0
  sfgov_about: 0
  sfgov_admin: 0
  sfgov_alerts: 0
  sfgov_amplitude: 0
  sfgov_campaigns: 0
  sfgov_departments: 0
  sfgov_design_system: 0
  sfgov_doc_html: 0
  sfgov_event_subscriber: 0
  sfgov_formio: 0
  sfgov_image_attributes: 0
  sfgov_locations: 0
  sfgov_media: 0
  sfgov_moderation: 0
  sfgov_news: 0
  sfgov_profiles: 0
  sfgov_public_bodies: 0
  sfgov_qless: 0
  sfgov_search: 0
  sfgov_user: 0
  sfgov_utilities: 0
  sfgov_vaccine: 0
  sfgov_video: 0
  shortcut: 0
  simple_block: 0
  simple_gmap: 0
  simple_instagram_feed: 0
  simple_sitemap: 0
  simplesamlphp_auth: 0
  smart_date: 0
  smart_trim: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  telephone: 0
  telephone_formatter: 0
  telephone_validation: 0
  text: 0
  time_range: 0
  tmgmt: 0
  tmgmt_content: 0
  tmgmt_contentapi: 0
  toc_api: 0
  toc_filter: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  video_embed_field: 0
  viewfield: 0
  views_bulk_operations: 0
  views_conditional: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflows: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  color_field: 10
  content_translation: 10
  externalauth: 10
  formdazzle: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  sfgovpl: 0
profile: standard
