module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  config_direct_save: 0
  config_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gnode: 0
  group: 0
  gtranslate: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  link: 0
  locale: 0
  mailsystem: 0
  mandrill: 0
  maxlength: 0
  media: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  path: 0
  redirect: 0
  search_api: 0
  search_api_pantheon: 0
  search_api_solr: 0
  sfgov_admin: 0
  sfgov_departments: 0
  shortcut: 0
  simple_block: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  telephone_formatter: 0
  telephone_validation: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  sfgovpl: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
