enabled_entity_types:
  media: media
  node: node
  taxonomy_term: taxonomy_term
  paragraph: paragraph
  location: location
  resource: resource
disabled_entity_types:
  block_content: 0
  content_moderation_state: 0
  unmanaged_files: 0
  file: 0
  group: 0
  group_content: 0
  job_schedule: 0
  path_alias: 0
  redirect: 0
  search_api_task: 0
  shortcut: 0
  tmgmt_job_item: 0
  tmgmt_remote: 0
  tmgmt_job: 0
  tmgmt_message: 0
  user: 0
  webform_submission: 0
  menu_link_content: 0
max_depth: '10'
