_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - media
  - node
  - taxonomy_term
  - paragraphs_type
track_enabled_source_entity_types:
  - node
  - content_moderation_state
  - block_content
  - menu_link_content
  - file
  - job_schedule
  - location
  - media
  - paragraph
  - paragraphs_type
  - redirect
  - resource
  - search_api_task
  - shortcut
  - taxonomy_term
  - tmgmt_job
  - tmgmt_job_item
  - tmgmt_message
  - tmgmt_remote
  - unmanaged_files
  - path_alias
track_enabled_target_entity_types:
  - node
  - content_moderation_state
  - block_content
  - menu_link_content
  - job_schedule
  - location
  - media
  - paragraph
  - paragraphs_type
  - redirect
  - resource
  - search_api_task
  - shortcut
  - taxonomy_term
  - tmgmt_job
  - tmgmt_job_item
  - tmgmt_message
  - tmgmt_remote
  - unmanaged_files
  - path_alias
track_enabled_plugins:
  - block_field
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - layout_builder
  - link
  - linkit
  - media_embed
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
