_core:
  default_config_hash: rHbHZIIF9TP3H2Vs37uCHz4Gm4phULg0rQ_OKihxJfM
extlink_use_external_js_file: false
extlink_exclude_admin_routes: false
extlink_target: true
extlink_target_no_override: false
extlink_nofollow: false
extlink_noreferrer: false
extlink_follow_no_override: false
extlink_subdomains: true
extlink_alert: false
extlink_alert_text: 'This link will take you to an external web site. We are not responsible for their content.'
extlink_exclude: '(social\.sf\.gov)|(\*\.social\.sf\.gov)|(social\.staging\.\*\.sf\.gov)'
extlink_include: ''
extlink_class: '0'
extlink_label: '(link is external)'
extlink_img_class: false
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_mailto_class: '0'
extlink_mailto_label: '(link sends email)'
extlink_use_font_awesome: false
extlink_font_awesome_classes: null
extlink_icon_placement: before
whitelisted_domains:
  - staging.social.sf.gov
  - social.sf.gov
  - social.staging.dev.sf.gov
links: 'fa fa-external-link'
mailto: 'fa fa-envelope-o'
