gtranslate_method: onfly
gtranslate_pro: 0
gtranslate_enterprise: 0
gtranslate_analytics: 0
gtranslate_look: links
gtranslate_flag_size: '16'
gtranslate_new_window: 0
gtranslate_main_lang: en
gtranslate_af: '0'
gtranslate_sq: '0'
gtranslate_ar: '0'
gtranslate_hy: '0'
gtranslate_az: '0'
gtranslate_eu: '0'
gtranslate_be: '0'
gtranslate_bg: '0'
gtranslate_ca: '0'
gtranslate_zh-CN: '0'
gtranslate_zh-TW: '1'
gtranslate_hr: '0'
gtranslate_cs: '0'
gtranslate_da: '0'
gtranslate_nl: '0'
gtranslate_en: '1'
gtranslate_et: '0'
gtranslate_tl: '1'
gtranslate_fi: '0'
gtranslate_fr: '0'
gtranslate_gl: '0'
gtranslate_ka: '0'
gtranslate_de: '0'
gtranslate_el: '0'
gtranslate_ht: '0'
gtranslate_iw: '0'
gtranslate_hi: '0'
gtranslate_hu: '0'
gtranslate_is: '0'
gtranslate_id: '0'
gtranslate_ga: '0'
gtranslate_it: '0'
gtranslate_ja: '0'
gtranslate_ko: '0'
gtranslate_lv: '0'
gtranslate_lt: '0'
gtranslate_mk: '0'
gtranslate_ms: '0'
gtranslate_mt: '0'
gtranslate_no: '0'
gtranslate_fa: '0'
gtranslate_pl: '0'
gtranslate_pt: '0'
gtranslate_ro: '0'
gtranslate_ru: '0'
gtranslate_sr: '0'
gtranslate_sk: '0'
gtranslate_sl: '0'
gtranslate_es: '1'
gtranslate_sw: '0'
gtranslate_sv: '0'
gtranslate_th: '0'
gtranslate_tr: '0'
gtranslate_uk: '0'
gtranslate_ur: '0'
gtranslate_vi: '0'
gtranslate_cy: '0'
gtranslate_yi: '0'
gtranslate_bn: '0'
gtranslate_bs: '0'
gtranslate_ceb: '0'
gtranslate_eo: '0'
gtranslate_gu: '0'
gtranslate_ha: '0'
gtranslate_hmn: '0'
gtranslate_ig: '0'
gtranslate_jw: '0'
gtranslate_kn: '0'
gtranslate_km: '0'
gtranslate_lo: '0'
gtranslate_la: '0'
gtranslate_mi: '0'
gtranslate_mr: '0'
gtranslate_mn: '0'
gtranslate_ne: '0'
gtranslate_pa: '0'
gtranslate_so: '0'
gtranslate_ta: '0'
gtranslate_te: '0'
gtranslate_yo: '0'
gtranslate_zu: '0'
gtranslate_my: '0'
gtranslate_ny: '0'
gtranslate_kk: '0'
gtranslate_mg: '0'
gtranslate_ml: '0'
gtranslate_si: '0'
gtranslate_st: '0'
gtranslate_su: '0'
gtranslate_tg: '0'
gtranslate_uz: '0'
gtranslate_am: '0'
gtranslate_co: '0'
gtranslate_haw: '0'
gtranslate_ku: '0'
gtranslate_ky: '0'
gtranslate_lb: '0'
gtranslate_ps: '0'
gtranslate_sm: '0'
gtranslate_gd: '0'
gtranslate_sn: '0'
gtranslate_sd: '0'
gtranslate_fy: '0'
gtranslate_xh: '0'
_core:
  default_config_hash: QfRxCsHzZ8_TOqax9jYAfQvj5Kq9Ve7vl4pVziKemhA
