_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: email
time_limit: 0
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  node_about_form: false
  node_campaign_form: false
  node_data_story_form: false
  node_department_form: false
  node_department_table_form: false
  node_event_form: false
  node_form_confirmation_page_form: false
  node_form_page_form: false
  node_information_page_form: false
  node_landing_form: false
  node_location_form: false
  node_meeting_form: false
  node_news_form: false
  node_page_form: false
  node_person_form: false
  node_public_body_form: false
  node_report_form: false
  node_resource_collection_form: false
  node_step_by_step_form: false
  node_topic_form: false
  node_transaction_form: false
