session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    fil: fil
    zh-hant: zh-hant
  domains:
    en: ''
    es: ''
    fil: ''
    zh-hant: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
