_core:
  default_config_hash: OK40vx3JjcqEDIm6xwvNwGt61EenZLBJ5rX9aijGI_0
login_message: 'Sorry you can not login now due to maintenance work, please try to login later.'
logout_message: 'Sorry, you have been logged out due to maintenance work, please try to login later.'
status_message: 'Operating while enabled login lock.'
redirect_url: /
roles_bypass_type: exclusive
roles_bypass: {  }
