_core:
  default_config_hash: 6XRelHPjACQVOo9yRQMmbXt-ysCA2Pt6l762bxQQbdw
exclude:
  node:
    person:
      - field_profile_positions_held
  paragraph: {  }
text_to_prepend_to_title: 'Copy:'
clone_status: false
