api_url: ''
error_message: 'We are having trouble reaching the service right now. Please try again later.'
title: 'Wait Times'
caption: 'The Permit Center uses Qless to manage customer lines and wait times.'
thead1: 'Queue'
thead2: 'Wait time'
footer_label: 'Last updated'
