api_url: 'https://sfgov-vaccine-sites.herokuapp.com/api/v1/appointments'
error_message: 'We are having trouble reaching the service right now. Please try again later.'
languages:
  all:
    site_label: null
    filter_label: 'Any language'
  en:
    site_label: English
    filter_label: English
  es:
    site_label: Spanish
    filter_label: 'Español (Spanish)'
  zh:
    site_label: Chinese
    filter_label: '中文 (Chinese)'
  ko:
    site_label: Korean
    filter_label: '한국어 (Korean)'
  fil:
    site_label: Filipino
    filter_label: Filipino
  vi:
    site_label: Vietnamese
    filter_label: 'Tiếng Việt (Vietnamese)'
  asl:
    site_label: ASL
    filter_label: ASL
  rt:
    site_label: null
    filter_label: 'Other Languages'
kids5to11:
  true_text: 'age 5 to 11'
minors:
  true_text: '12 and older'
  false_text: '18 and older'
access_mode:
  walk:
    short_key: wa
    text: Walk-thru
  drive:
    short_key: dr
    text: Drive-thru
  all:
    short_key: all
    text: 'Drive-thru or walk-thru'
  wheelchair:
    short_key: wh
    text: 'Wheelchair accessible'
radius:
  all:
    value: Infinity
    text: 'Any distance'
  1:
    value: '.5'
    text: '0.5 mile'
  2:
    value: 1
    text: '1 mile'
  3:
    value: 3
    text: '3 miles'
form_strings:
  title: Filters
  restrictions: 'Only show sites open to the general public'
  kids5to11: 'Vaccines for kids age 5 to 11'
  available: 'Open appointment or drop-in'
  language_label: 'Languages spoken'
  access_mode_label: Access
  eligibility_label: 'Eligibility requirements'
  distance_label: 'Sort by distance'
  location_label: 'Enter address or zip'
  submit_label: Apply
template_strings:
  page:
    title: 'COVID-19 vaccine sites'
    description: 'Find out where to get a vaccine. If you need a second dose, contact the location where you got your first dose. <a href=''https://sf.gov/covid-19-vaccine-san-francisco''>Learn more</a>'
    alert:
      value: "<p>You must be eligible in order to get vaccinated. <a href=\"/getvaccinated\">See eligibility criteria</a></p>\r\n"
      format: sf_restricted_html
    empty:
      text_1: 'No sites match your search'
      text_2: 'Remove some of the filters to find more sites.'
      text_3: 'You can also see more options to get vaccinated.'
  result:
    access_modes:
      label: Access
    info_url:
      label: 'Learn more about this location'
    languages:
      label: 'Languages spoken'
    phone:
      label: 'Or call'
    brands:
      label: 'Expected vaccines'
