api_url: 'https://vaccination-site-microservice.vercel.app/api/v1/appointments'
error_message: 'We are having trouble reaching the service right now. Please try again later.'
languages:
  all:
    site_label: null
    filter_label: 'Any language'
  en:
    site_label: English
    filter_label: English
  es:
    site_label: Spanish
    filter_label: Español (Spanish)
  zh:
    site_label: Chinese
    filter_label: 中文 (Chinese)
  ko:
    site_label: Korean
    filter_label: 한국어 (Korean)
  fil:
    site_label: Filipino
    filter_label: Filipino
  vi:
    site_label: Vietnamese
    filter_label: Tiếng Việt (Vietnamese)
  asl:
    site_label: ASL
    filter_label: ASL
  rt:
    site_label: null
    filter_label: 'Other Languages'
eligibility:
  65_and_over:
    short_key: sf
    text: 65 and over
  healthcare_workers:
    short_key: hw
    text: Healthcare workers
  education_and_childcare:
    short_key: ec
    text: Education and childcare
  agriculture_and_food:
    short_key: af
    text: Agriculture and food
  emergency_services:
    short_key: es
    text: Emergency services
  health_condition:
    short_key: hc
    text: Eligible health conditions
access_mode:
  walk:
    short_key: wa
    text: Walk-thru
  drive:
    short_key: dr
    text: Drive-thru
  all:
    short_key: all
    text: 'Drive-thru or walk-thru'
  wheelchair:
    short_key: wh
    text: Wheelchair accessible

form_strings:
  title: Filters
  restrictions: 'Only show sites open to the general public'
  available: 'Only show sites with confirmed availability'
  language_label: Languages spoken
  access_mode_label: Access
  eligibility_label: Eligibility requirements
  submit_label: Apply

template_strings:
  page:
    title: COVID-19 vaccine sites
    description: "Find out where to get a vaccine if you're eligible. Keep checking for appointments. New locations will be added as they're available.  If you need a second dose, contact the location where you got your first dose.  <a href=/covid-19-vaccine-san-francisco>Learn more.</a>"
    alert: "You must be eligible in order to get vaccinated. <a href=/getvaccinated>See eligibility criteria</a>"
    empty:
      text_1: No sites match your search
      text_2: Remove some of the filters to find more sites.
      text_3: You can also see more options to get vaccinated.
  result:
    access_modes:
      label: Access
    info_url:
      label: Learn more about this location
    languages:
      label: Languages spoken
