features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
favicon:
  use_default: 1
enable_darkmode: 1
preset_accent_color: null
accent_color: ''
preset_focus_color: custom
focus_color: 4f66ee
high_contrast_mode: 0
show_user_theme_settings: 0
classic_toolbar: '1'
icon_default: 1
icon_upload: ''
