username: admin
password: admin
host_ip: host.docker.internal
port: '8000'
wag_parent_en: '2'
wag_parent_es: '3'
wag_parent_fil: '4'
api_url_base: 'http://host.docker.internal:8000/api/cms/'
wag_parent_zh_hant: '5'
