_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
max_links: 1000
cron_generate: false
cron_generate_interval: 0
generate_duration: 10000
entities_per_queue_item: 10
remove_duplicates: true
skip_untranslated: true
xsl: true
base_url: 'https://www.sf.gov'
default_variant: map
custom_links_include_images: false
disable_language_hreflang: false
hide_branding: true
excluded_languages: {  }
enabled_entity_types:
  - taxonomy_term
  - menu_link_content
  - node
batch_process_limit: 1500
