_core:
  default_config_hash: BuLah1nwoT5oUjn6XIuKnXkjcvdt5tDIGQ6gAflOY0s
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Federated login'
login_link_show: false
user_name: email
unique_id: email
mail_attr: email
header_no_cache: false
role:
  population: ''
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: false
  default_login: true
  default_login_roles:
    authenticated: authenticated
    administrator: administrator
    writer: '0'
    publisher: '0'
  default_login_users: ''
logout_goto_url: ''
user_register_original: visitors_admin_approval
sync:
  mail: true
  user_name: true
autoenablesaml: true
debug: true
secure: false
httponly: false
