_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 3babad38-e3d2-427a-8263-5df1d347665a
name: 'San Francisco'
mail: noreply@sfgov.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/15469
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
