embedded_fields:
  block_content:
    revision_user: true
    content_translation_uid: true
  media:
    revision_user: true
    uid: true
    field_department: true
  node:
    revision_uid: true
    uid: true
    field_address: true
    field_departments: true
    field_dept: true
    field_divisions: true
    field_image: true
    field_parent_department: true
    field_tags: true
    field_topics: true
    field_transactions: true
  taxonomy_term:
    revision_user: true
    parent: true
    content_translation_uid: true
  user:
    content_translation_uid: true
  menu_link_content:
    revision_user: true
    content_translation_uid: true
  paragraph:
    field_dept_service_sect_services: true
    field_file: true
    field_location: true
    field_media: true
    field_person: true
    field_person_2: true
    field_spotlight_img: true
    field_transaction: true
  location:
    uid: true
_core:
  default_config_hash: Yx-6uSwgH5itKuJtsVkruGtgxz3SFbDHST6V6qzlKxw
