<?php

/**
 * @file
 * Contains sfgov_public_bodies.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sfgov_public_bodies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sfgov_public_bodies module.
    case 'help.page.sfgov_public_bodies':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SF Gov Public Bodies') . '</p>';
      return $output;

    default:
  }
}
