#!/bin/bash

set -eo pipefail

PORT=2222
UUID=$(terminus site:lookup $TERMINUS_SITE)
SAML_ENV=TERMINUS_ENV

if [[ $CIRCLE_BRANCH != "main" ]] ; then
  SAML_ENV=dev
fi

sftp -o PORT=$PORT $SAML_ENV.$UUID@appserver.$SAML_ENV.$UUID.drush.in <<EOF
get -r files/private/saml
cd code/web/private
mkdir metadata
put -r ./saml/*
exit
EOF
