#!/bin/bash

set -eo pipefail

PORT=2222
UUID=$(terminus site:lookup $TERMINUS_SITE)

sftp -o PORT=$PORT $TERMINUS_ENV.$UUID@appserver.$TERMINUS_ENV.$UUID.drush.in <<EOF
get -r files/private/saml
cd code/web/private
mkdir metadata
put -r ./saml/*
exit
EOF
