title: Number field
context:
  title: How many months do you estimate it will take you to build the ADU?
  id: construction_duration
variants:
  - name: With units
    context:
      title: How long do you estimate it will take you to build the ADU?
      units: months
