context:
  colorset:
    - label: $black
      color: "#212123"
    - label: $slate
      color: "#1c3e57"
    - label: $dark-blue
      color: "#0c1464"
    - label: $bright-blue
      color: "#4f66ee"
    - label: $blue-2
      color: "#a9d6ea"
    - label: $blue-1
      color: "#edf4f7"
    - label: $green-4
      color: "#1b674d"
    - label: $green-3
      color: "#00896d"
    - label: $green-2
      color: "#c0e2c5"
    - label: $green-1
      color: "#e9f7ec"
    - label: $red-4
      color: "#bc4427"
    - label: $red-3
      color: "#c9563a"
    - label: $red-2
      color: "#efcabb"
    - label: $red-1
      color: "#f5e9e5"
    - label: $purple-4
      color: "#5a3e94"
    - label: $purple-3
      color: "#7d61b3"
    - label: $purple-2
      color: "#cccced"
    - label: $purple-1
      color: "#edebf6"
    - label: $yellow-4
      color: "#e7b22e"
    - label: $yellow-3
      color: "#f4c435"
    - label: $yellow-2
      color: "#f9e3a3"
    - label: $yellow-1
      color: "#f8f1df"
    - label: $grey-4
      color: "#d3d3d3"
    - label: $grey-3
      color: "#e9e9e9"
    - label: $grey-2
      color: "#f1f1f1"
    - label: $grey-1
      color: "#f8f8f8"
    - label: $white
      color: "#ffffff"