#!/bin/bash

repo="$CIRCLE_PROJECT_REPONAME"
slug="${CIRCLE_PROJECT_USERNAME}/${repo}"
sha="$CIRCLE_SHA1"
token="$GITHUB_TOKEN"
target_url="$MULTIDEV_SITE_URL"

env='multidev'
transient='true'
auto_inactive='true'

if [ "$CIRCLE_BRANCH" = "main" ]; then
  env='production'
  transient='false'
  production='true'
  auto_inactive='false'
  target_url="https://sf.gov"
fi

data='{
  "ref": "'"$sha"'",
  "environment": "'"$env"'",
  "auto_merge": false,
  "transient_environment": '$transient',
  "required_contexts": []
}'
echo "deployment JSON: $data"

deployment=$(
  curl -s \
    -d "$data" \
    -H "Accept: application/vnd.github.ant-man-preview+json" \
    -X POST "https://api.github.com/repos/$slug/deployments?access_token=$token" \
)

echo "deployment: $deployment"

statuses_url="$(echo "$deployment" | jq -r .statuses_url)"
if [ -n "$statuses_url" ]; then
  echo "Got statuses_url: '$statuses_url'; setting status..."
  data='{
    "state": "success",
    "target_url": "'"$target_url"'",
    "environment": "'"$env"'",
    "environment_url": "'"$target_url"'",
    "auto_inactive": '$auto_inactive'
  }'
  echo "status data: $data\nresponse:"
  curl -s \
    -H "Accept: application/vnd.github.flash-preview+json" \
    -d "$data" \
    -X POST "$statuses_url?access_token=$token"
else
  echo "No statuses_url found; skipping deploy status"
fi
