#!/bin/bash

repo="$CIRCLE_PROJECT_REPONAME"
slug="${CIRCLE_PROJECT_USERNAME}/${repo}"
sha="$CIRCLE_SHA1"
token="$GITHUB_TOKEN"
target_url="https://pr-${CIRCLE_PR_NUMBER}-${repo}.pantheonsite.io"

env=test
transient=true
auto_inactive=true

if [ "$CIRCLE_BRANCH" = "main" ]; then
  env=production
  transient=false
  auto_inactive=false
  target_url="https://sf.gov"
fi

echo "Hi! Here is the state of things:

  repo: '$repo'
  slug: '$slug'
  sha: '$sha'
  token: '(masked)'
  target_url: '$target_url'"

deployment=$(
  curl -s \
    -H "Accept: application/vnd.github.ant-man-preview+json" \
    -d '{ "ref": "'"$sha"'", "environment": "'"$env"'", "transient_environment": '$transient' }' \
    -X POST "https://api.github.com/repos/$slug/deployments?access_token=$token" \
)

echo "deployment: $deployment"

statuses_url="$(echo "$deployment" | jq -r .statuses_url)"
if [ -n "$statuses_url" ]; then
  echo "Got statuses_url: '$statuses_url'; setting status..."
  curl -s \
    -H "Accept: application/vnd.github.flash-preview+json" \
    -d '{ "state": "success", "target_url": "'"$target_url"'", "environment": "'"$env"'", "auto_inactive": '$auto_inactive' }' \
    -X POST "$statuses_url?access_token=$token"
  echo
else
  echo "No statuses_url found; skipping deploy status"
fi
