<?php

/**
 * Implements hook_page_attachments().
 */
function sfgov_readability_page_attachments(array &$attachments) {
  $loggedInUser = \Drupal::currentUser()->isAuthenticated();
  $isEditPage = basename(\Drupal::service('path.current')->getPath()) === 'edit';
  $isContentNode = !empty(\Drupal::routeMatch()->getParameter('node'));

  if($loggedInUser && $isContentNode && !$isEditPage) {
    $attachments['#attached']['library'][] = 'sfgov_readability/main';
  }
}
