tmgmt.translator.settings.file:
  type: tmgmt.translator_base
  mapping:
    export_format:
      type: string
      label: Default export format
    allow_override:
      type: boolean
      label: Allow override of export format
    scheme:
      type: string
      label: Stream wrapper scheme
    xliff_processing:
      type: boolean
      label: Xliff HTML processing
    xliff_cdata:
      type: boolean
      label: Xliff CDATA
    format_configuration:
      type: mapping
      label: Format configuration
      mapping:
        target:
          type: string
          label: Target content
