<?php

/**
 * @file
 * Implements hook for sfgov_media module.
 */

/**
 * Implements hook_theme().
 */
function sfgov_media_theme($existing, $type, $theme, $path) {
  return [
    'media_power_bi' => [
      'variables' => [
        'url' => NULL,
        'device' => NULL,
        'width' => NULL,
        'height' => NULL,
      ],
      'file' => 'sfgov_media.theme.inc',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_media_preprocess_paragraph(&$variables) {
  // Temp code for testing embed aspect ratio.
  $variables['is_test'] = $variables['paragraph']->bundle() === "power_bi_chart" && Drupal::request()
      ->getRequestUri() === "/power-bi-embed";
}
