# Schema for the configuration files of the sfgov_api module.
sfgov_api.settings:
  type: config_object
  label: 'sfgov_api settings'
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    host_ip:
      type: string
      label: 'Host IP'
    port:
      type: string
      label: 'Port'
    wag_parent_en:
      type: string
      label: 'WAG Parent EN'
    wag_parent_es:
      type: string
      label: 'WAG Parent ES'
    wag_parent_zh:
      type: string
      label: 'WAG Parent ZH'
    wag_parent_fil:
      type: string
      label: 'WAG Parent FIL'
    api_url_base:
      type: string
      label: 'API URL Base'
