toc_api.toc_type.*:
  type: config_entity
  label: 'Table of contents type'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    options:
      type: mapping
      label: 'Options (YAML)'
      mapping:
        template:
          type: string
          label: 'Template'
        title:
          type: label
          label: 'Title'
        block:
          type: boolean
          label: 'Display in block'
        header_count:
          type: integer
          label: 'Minimum number of headers'
        header_min:
          type: integer
          label: 'Header minimum level'
        header_max:
          type: integer
          label: 'Header maximum level'
        header_allowed_tags:
          type: string
          label: 'Allowed HTML tags'
        header_id:
          type: string
          label: 'Header ID type'
        header_id_prefix:
          type: string
          label: 'Header ID prefix'
        top_label:
          type: string
          label: 'Back to top'
        top_min:
          type: integer
          label: 'Back to top minimum header level'
        top_max:
          type: integer
          label: 'Back to top maximum header level'
        number_path:
          type: boolean
          label: 'Numbering path'
        number_path_separator:
          type: string
          label: 'Numbering path separator'
        number_path_truncate:
          type: boolean
          label: 'Numbering path truncate'
        default:
          type: mapping
          label: 'Default header'
          mapping:
            number_type:
              type: string
              label: 'Numbering type'
            number_prefix:
              type: string
              label: 'Numbering prefix'
            number_suffix:
              type: string
              label: 'Numbering suffix'
        headers:
          label: 'Headers (h1 - h6)'
          type: mapping
          mapping:
            h1:
              type: ignore
            h2:
              type: ignore
            h3:
              type: ignore
            h4:
              type: ignore
            h5:
              type: ignore
            h6:
              type: ignore
