name: Configuration Exclude
type: module
description: Filter for excluding modules and dependent configuration during config export
core: 8.x
package: Config
dependencies:
  - config_filter:config_filter
