#!/bin/bash

set -eo pipefail

samlConfig=$(pwd)"/vendor/simplesamlphp/simplesamlphp/config"
samlMetadata=$(pwd)"/vendor/simplesamlphp/simplesamlphp/metadata"

samlTestConfig="files/private/saml/test/config"
samlTestMetadata="files/private/saml/test/metadata"
samlLiveConfig="files/private/saml/live/config"
samlLiveMetadata="files/private/saml/live/metadata"

syncConfig=$samlTestConfig
syncMetadata=$samlTestMetadata

if [[ $TERMINUS_ENV == "live" ]] ; then
  syncConfig=$samlLiveConfig
  syncMetadata=$samlLiveMetadata
fi

terminus rsync $TERMINUS_SITE.live:$syncConfig $samlConfig
terminus rsync $TERMINUS_SITE.live:$syncMetadata $samlMetadata
