#!/bin/bash

set -eo pipefail

samlTestConfig=$(pwd)"/web/sites/default/files/private/saml/test/config"
samlTestMetadata=$(pwd)"/web/sites/default/files/private/saml/test/metadata"
samlLiveConfig=$(pwd)"/web/sites/default/files/private/saml/live/config"
samlLiveMetadata=$(pwd)"/web/sites/default/files/private/saml/live/metadata"

samlConfig=$(pwd)"/vendor/simplesamlphp/simplesamlphp/config"
samlMetadata=$(pwd)"/vendor/simplesamlphp/simplesamlphp/metadata"

# remove existing simplesamlphp config and metadata directories
rm -vrf $samlConfig
rm -vrf $samlMetadata

# create necessary (empty) directories to symlink
mkdir -vp $samlTestConfig
mkdir -vp $samlTestMetadata
mkdir -vp $samlLiveConfig
mkdir -vp $samlLiveMetadata

linkConfig=$samlTestConfig
linkMetadata=$samlTestMetadata

if [[ $TERMINUS_ENV == "live" ]] ; then
  linkConfig=$samlLiveConfig
  linkMetadata=$samlLiveMetadata
fi

# symlink config and metadata
ln -vsfn $linkConfig $samlConfig
ln -vsfn $linkMetadata $samlMetadata
