#!/bin/bash
for path in $@; do
  if egrep '/[\*/] .*purgecss .*ignore' $path; then
    echo "- skipping $path: the file already has purgecss comments"
    continue
  fi
  if egrep -v '@import' $path; then
    echo "+ wrapping $path in purgecss ignore comments"
    (
      echo '/* purgecss start ignore */'
      cat $path
      echo '/* purgecss end ignore */'
    ) > "$path.tmp"
    mv "$path.tmp" $path
  fi
done
