anonymous_redirect.settings:
  type: config_object
  mapping:
    enable_redirect:
      type: boolean
      label: 'Enable Redirect'
    redirect_url:
      type: string
      label: 'Redirect Url'
    langcode:
      type: string
      label: 'Language Code'