amplitude.amplitude_event.*:
  type: config_entity
  label: 'Amplitude event config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    properties:
      type: string
      label: 'Event properties'
    event_trigger:
      type: string
      label: 'Event trigger'
    event_trigger_pages:
      type: string
      label: 'Event pages'
    event_trigger_scroll_depths:
      type: string
      label: 'Event trigger scroll depths'
    event_trigger_other:
      type: string
      label: 'Custom event trigger'
    event_trigger_selector:
      type: string
      label: 'Event trigger selector'
    event_trigger_data_capture:
      type: string
      label: 'Event trigger data capture'
    event_trigger_data_capture_properties:
      type: string
      label: 'Event trigger data capture selector'
