<?php

/**
 * @file
 * Drupal Module: Simple Instagram Feed.
 *
 * Simple Instagram Feed is a module that
 * provides blocks to display instagram
 * feeds.
 *
 * author: Andrew Wasson <https://drupal.org/user/127091>
 */

/**
 * Implements hook_theme().
 */
function simple_instagram_feed_theme($existing, $type, $theme, $path) {
  $variables = [
    'simple_instagram_block' => [
      'variables' => [
        'markup' => [],
        'unique_id' => NULL,
      ],
    ],
  ];
  return $variables;
}
