<?php

/**
 * @file
 * Main module file for the Translation Management Demo module.
 */

/**
 * Implements hook_theme().
 */
function tmgmt_demo_theme() {
  return [
    'tmgmt_demo_text' => array(
      'variables' => array(
        'content_language' => NULL,
        'languages_url' => NULL,
        'translatable_nodes' => NULL,
        'translate_url' => NULL,
        'file_translator' => NULL,
        'tmgmt_local' => NULL,
      ),
    ),
  ];
}
