label: Checkboxes
context:
  id: will_the_work_involve
  title: Will the work involve any of the following?
  options:
  - title: Repairing or replacing the building's foundation

  - title: Building a driveway or auto runway

  - title: Using street space

  - title: Changing the front facade

  - title: Repairing or changing the sidewalk above a basement
