<?php

/**
 * Implements hook_preprocess_views().
 *
 * Workaround to display the Views title.
 * See https://www.drupal.org/project/drupal/issues/2887071#comment-13554107
 */
function sfgov_services_preprocess_views_view__services__services_search(&$variables) {
  $view = $variables['view'];
  $view_id = $variables['id'];
  $view_display_id = $variables['display_id'];

  $variables['filters'] = \Drupal::formBuilder()->getForm('Drupal\sfgov_services\Form\ServicesSearchFiltersForm');
}

/**
 * Implements hook_views_query_alter().
 */
function sfgov_services_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  if ($view->id() == 'services' && $view->getDisplay()->display['id'] == 'services_search') {
    $query_topics = \Drupal::request()->query->get('topics');
    $query_departments = \Drupal::request()->query->get('departments');

    foreach ($query->where as $group => $where) {
      // Add filters for Topics.
      if ($query_topics) {
        $query->addTable("node__field_topics");
        $query->addWhere($group, 'node__field_topics.field_topics_target_id', array_values($query_topics), 'in');
      }

      // Add filters for Departments.
      if ($query_departments) {
        $query->addTable("node__field_departments");
        $query->addWhere($group, 'node__field_departments.field_departments_target_id', array_values($query_departments), 'in');
      }
    }
  }
}