<?php

/**
 * Implements hook_preprocess_views().
 *
 * Workaround to display the Views title.
 * See https://www.drupal.org/project/drupal/issues/2887071#comment-13554107
 */
function sfgov_services_preprocess_views_view__services__services_search(&$variables) {
  $view = $variables['view'];
  $view_id = $variables['id'];
  $view_display_id = $variables['display_id'];

  $variables['filters'] = \Drupal::formBuilder()->getForm('Drupal\sfgov_services\Form\ServicesSearchFiltersForm');
}
