field.widget.settings.sfgov_customizable_paragraphs:
  type: mapping
  mapping:
    title:
      type: label
    title_plural:
      type: label
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_paragraph_type:
      type: string
    paragraph_settings:
      type: sequence
      sequence:
        type: mapping
        mapping:
          field_settings:
            type: sequence
            sequence:
              type: mapping
              mapping:
                label:
                  type: string
                target_bundles:
                  type: sequence
                  orderby: key
                  sequence:
                    type: string

