<?php

/**
 * @file
 * Contains sfgov_vaccine.module.
 */

/**
 * Defaults for settings form.
 */
function sfgov_vaccine_update_8001() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('sfgov_vaccine.settings');
  $config->set('api_url','https://vaccination-site-microservice.vercel.app/api/v1/appointments');
  $config->save(TRUE);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_vaccine_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route == 'sfgov_vaccine.vaccine_controller_display_page') {
    $variables['attributes']['class'][] = 'page-sfgov-vaccine-sites';
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_vaccine_theme() {
  return [
    'vaccine_widget' => [
      'variables' => [
        'page_title' => NULL,
        'filters' => NULL,
        'results' => NULL,
        'api_data' => NULL
      ],
    ],
  ];
}

