<?php

/**
 * @file
 * Contains sfgov_vaccine.module.
 */

use Drupal\Core\Site\Settings;

/**
 * Defaults for settings form.
 */
function sfgov_vaccine_update_8001() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('sfgov_vaccine.settings');
  $config->set('api_url', 'https://sfgov-vaccine-sites.herokuapp.com/api/v1/appointments');
  $config->save(TRUE);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_vaccine_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route == 'sfgov_vaccine.vaccine_controller_display_page') {
    $variables['attributes']['class'][] = 'page-sfgov-vaccine-sites';
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_vaccine_theme() {
  return [
    'vaccine_widget' => [
      'variables' => [
        'alert' => NULL,
        'header_description' => NULL,
        'template_strings' => NULL,
        'filters' => NULL,
        'results' => NULL,
        'api_data' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function sfgov_vaccine_library_info_alter(&$libraries, $extension) {

  // Dynamically add gmaps script to filter library.
  $google_places_api_key = Settings::get('google_places_api_key');
  $gmaps_url = sprintf("//maps.googleapis.com/maps/api/js?key=%s&callback=locationAutocomplete&libraries=places&v=weekly", $google_places_api_key);

  if (isset($libraries['location'])) {
    $libraries['location']['js'][$gmaps_url] = [
      'attributes' => [
        'async' => TRUE,
      ],
    ];
  }
}
