<?php

/**
 * @file
 * Contains sfgov_vaccine.module.
 */


/**
 * Implements hook_preprocess_HOOK().
 */
function sfgov_vaccine_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route == 'sfgov_vaccine.vaccine_controller_display_page') {
    $variables['attributes']['class'][] = 'page-sfgov-vaccine-sites';
  }
}

/**
 * Implements hook_theme().
 */
function sfgov_vaccine_theme() {
  return [
    'vaccine-widget' => [
      'variables' => [
        'page_title' => NULL,
        'filters' => NULL,
        'results' => NULL,
        'timestamp' => NULL
      ],
    ],
  ];
}

