name: Amplitude events
on:
  # - check_run
  # - check_suite
  - deployment_status
  - pull_request:
      types:
        - opened
        - closed
        - reopened
        - converted_to_draft
        - ready_for_review
        - review_request_removed
        - review_requested
  - push:
      tags: 'v*'
  - release:
      types:
        - published

jobs:
  log:
    runs-on: ubuntu-latest
    if: secrets.AMPLITUDE_API_KEY
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node@v2
        with:
          node-version: 14
      - name: npm install
        run: npm install @actions/{core,github} @amplitude/node
      - name: log amplitude event
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        run: ./scripts/custom/amplitude-event.js
