name: Amplitude events
on:
  deployment_status:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
  release:
    types:
      - created
      - published    

jobs:
  # This is a workaround for secrets not being accessible in workflow 'if'
  # expressions. It runs a 'check' job with a 'ready' output set to 'true'
  # if the secret is not empty, then conditionally runs the 'log' job if
  # the 'ready' output of the 'check' job == 'true'. Issue and explanation
  # here: https://github.com/actions/runner/issues/1138
  check:
    outputs:
      ready: ${{ steps.check.outputs.ready }}
    runs-on: ubuntu-latest
    steps:
      - id: check
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        if: env.AMPLITUDE_API_KEY != ''
        run: echo "::set-output name=ready::true"

  log:
    needs: [check]
    if: needs.check.outputs.ready == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node@v2
        with:
          node-version: 14
      - name: npm install
        run: npm install @actions/{core,github} @amplitude/node
      - name: log amplitude event
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        run: ./scripts/custom/amplitude-event.js
