name: Post e2e test tasks
on:
  check_suite:
    types: [completed]

jobs:
  event_data:
    runs-on: ubuntu-latest
    steps:
      - name: Print event data
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
