name: Lighthouse
on:
  deployment_status:
    types: [success]

jobs:
  lighthouse:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: event JSON
        run: echo '${{ toJson(github.event) }}'
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.deployment.sha }}
      - uses: treosh/lighthouse-ci-action@v3
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com
        env:
          LHCI_GITHUB_TOKEN: ${{ github.token }}
          LHCI_COLLECT_BASE_URL: ${{ github.event.deployment_status.target_url }}
