name: Lighthouse
on: [deployment_status]

jobs:
  lighthouse:
    # if: github.event.deployment_status.state == 'success'
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: determine branch
        uses: SFDigitalServices/git-the-branch@v1

      - uses: treosh/lighthouse-ci-action@v9
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ env.GIT_BRANCH }}
          LHCI_GITHUB_TOKEN: ${{ github.token }}
          LHCI_COLLECT_BASE_URL: ${{ github.event.deployment_status.target_url }}
