media.source.power_bi:
  type: media.source.field_aware
  label: 'Power BI media source configuration'

field.formatter.settings.power_bi:
  type: mapping
  label: 'Field display format settings'
  mapping:
    width:
      type: string
      label: 'Width'
    height:
      type: string
      label: 'Height'
